### ISSUE TITLE
Name conflict with time measurement device on the global python symbol `TimeTagger`

### ISSUE THREAD

**Issue by degasus** [almarklein/timetagger#103]
This package https://pypi.org/project/timetagger/ has a case-insensitive name conflict with the python interface of Swabian's time measurement device https://www.swabianinstruments.com/static/documentation/TimeTagger/index.html

Good luck, only the insensitive name conflicts, so both can be installed manually at the same time. But pip won't like it.

I agree, it's the fault of swabian for not registering their name on pip back in 2016.

But what is the common way to solve this kind of name conflicts?

**Comment by almarklein** [comment]
Hi, and thanks for the notification.

From a quick glance, it looks like Swabian's tool is an application, installed with an MSI, and not a Python package. Although a search on Pypi shows that Swabian has a lib called TimeTaggerRPC.

![image](https://user-images.githubusercontent.com/3015475/143025489-f56c92fb-bd29-4cd5-b27b-4464afe18792.png)

So, as far as I can see there are no name clashes, from a technical point of view. There is the fact that these two projects have the same name, but they are very different products so the chance that people will confuse the two is small.
 
> But what is the common way to solve this kind of name conflicts?

That depends on the situation. Personally I don't see a problem. If Swabian considers this situation a problem, they can reach out and see if we can work something out.

**Comment by degasus** [comment]
Hi, thanks for your answer.

I don't think this is a real issue, just one of our customer has somehow managed to execute `pip install timetagger` for controlling our hardware and was surprised of the outcome :)

I even like that even if our package name conflicts, our module name does not. So both can be installed at once.

**Comment by almarklein** [comment]
Ah, I see.

It looks like the readme of your project clearly mentions to `pip install TimeTaggerRPC`, and so do the docs. :+1:  so in theory it should be clear enough :)
