### ISSUE TITLE
Create new record via the timeline

### ISSUE THREAD

**Issue by PabloLION** [almarklein/timetagger#104]
## some background 

@almarklein and I discussed in #102  

> Click timeline to add event.
> (Almar:) We also had this is the past: if you clicked the timeline, it would go into a mode where you could drag the new record. This apparently was rather confusing for users. I'm definitely not opposed to bringing it back somehow, but I'm not sure how. If you have ideas on how to make this work well in combination with navigating the timeline, I would love to hear. A separate issue would be good here too.
> (Me:) I used toggl desktop, on windows it was correct and on Mac it's much worse. I totally understand the conflict of between dragging to adjust and clicking/dragging to add. I meant to ask you if you think it's good. If so, the rest is all UI/UX technique. Options are listed below.

## some options

1. Explicit interface but (maybe) no so friendly to mobile user. (this occured to me after 3-month thinking) 
- Advantage: low learning cost: very explicit UI and user should know what the elements represent.
- Disadvantage: technically we might need to rewrite all the data structure; less user friendly on mobile devices.
- Introducing "time node": entry (AKA a track, an event, or time entry. I prefer to reserve `event` since its a more frequent term in frontend dev, like "click event". Maybe we should use GitHub Wiki for dev purpose) always starts and ends on a time node. We can use some representation of `date` object.
- Use another column on the left side of current timeline to CRUD "time node"
  - Click: click on a time node to enter a precise time (with some parser); click not on a time node to create a new time node, moreover, hold the left click button and drag to adjust `date` of this new time node as if user is dragging the new time node.
  - Drag: drag starts from a time node to adjust `date` of this time node. Optionally zoom in the timeline if user hold more than 1 second or use apple video UI logic.
  - Double click: move time node to most recent minute divisible by 5, by 10 or by 15. 
  - Right click = long press: empty for now.
- After last step, we are able to 
  - Drag on timeline to browse, and drag to left/right to zoom in/out the timeline.
  - Click on timeline, if there is no entry between two time nodes to add a new entry, or show the entry.
  - Click on timeline, if there is an entry, then drag, on the entry to move entry between time nodes
  - Right click = long press : empty for now. But there are lots of options. 

2. Small upgrade interface
- Advantage: minimal UI change
- Disadvantage: not so explicit, indicator is relatively important 
- Add a indicator of [create/update] mode.
- Switch timeline [create/update] mode by clicking [somewhere or some button].

3. Add more interaction
- Advantage: no UI change at all
- Disadvantage: hard to learn; user needs more "clicks", hence worse UX.
- Click on an entry to select the entry, then click to edit (double click to edit). User can only change the time on selected entry
- Drag on the timeline to browse.
- Click on a non entry to start adding new entry. Then click(double click in total) to auto-fill or add an 1-hour entry with pop up. (this is not very explicit since user has to type then adjust time) 
- Right click = long press acts as a double click.

**Comment by almarklein** [comment]
I think I like I variation of (what I think you mean with) 2.

4. right-click / long-touch enables new-record-drag mode. In this mode you can drag the range for the new record.

**Comment by almarklein** [comment]
This is now implemented. I really like that this functionality is now back again!
