### ISSUE TITLE
filter for tags in report

### ISSUE THREAD

**Issue by mortbauer** [almarklein/timetagger#105]
I just found this app and am really amazed what you built, might be my future time tracking.

What wuild definitely be good would be to filter for tags for creating reports.

**Comment by mortbauer** [comment]
Ok, just realized it is possible, maybe directly editing the tags field in the report page would be nice

**Comment by almarklein** [comment]
I think this makes sense. At the very least it could be more clear how tags can (now) be selected.

**Comment by almarklein** [comment]
Implementing another tag selection mechanism is a bit much (in terms of time it'll cost me, and possibly also in complicating the UX), so I updated the shown text when no tags are selected, hopefully making it more clear what to do.

These changes are deployed in the current version online.
