### ISSUE TITLE
Database path configuration option

### ISSUE THREAD

**Issue by MisterY** [almarklein/timetagger#108]
Would it be possible to use a startup parameter to point to the SQLite database file?

The path could also be set in a configuration file or elsewhere.

**Comment by almarklein** [comment]
Good idea! More specifically, it should be a parameter to set the *directory* where the user db's are stored. 

I think the easiest way is to support CLI arguments or environment variables, or both.

**Comment by almarklein** [comment]
Fixed in #109. With that change you can now either set `TIMETAGGER_DATADIR` or use the `--datadir` CLI arg to set the root datadir. The user db's are in `datadir/users`.

**Comment by MisterY** [comment]
Thanks!
