### ISSUE TITLE
manual task entry start time reset

### ISSUE THREAD

**Issue by Floehe** [almarklein/timetagger#116]
Hi,

just noticed a new bug in the latest version 22.1.1. When manually recording a task with the option "Time - Already done", I enter the start time end the end time. After entering the end time, the start time automatically changes back to "01:00". I can re-edit the start time afterwards and then everything is ok.

All the best,
Florian

**Comment by almarklein** [comment]
Thanks for reporting this! I can indeed reproduce this. It also looks like sometime a time is interpreted as pm. Will look into this later today.

**Comment by almarklein** [comment]
Fix is deployed!

**Comment by Floehe** [comment]
thank you very much, it is working now as expected! :)
