### ISSUE TITLE
Sharing summaries (with clients or coworkers) via set of tags

### ISSUE THREAD

**Issue by dzmitry-lahoda** [almarklein/timetagger#118]
can i share specific tags with some specific another account? :) thanks

**Comment by almarklein** [comment]
Hi! Not directly. An approach could be to use the tag presets. 

![image](https://user-images.githubusercontent.com/3015475/149834136-c0d87e52-0de0-450b-a50a-bfad1e97f55f.png)

Assuming that you want to share your tags with someone else, 
you could prepare a list of tag combos that can simply be copy pasted in the preset list. The other person can then use them via the preset dropdown. And after doing this once, the tags will also appear in the list of recent tags.

Let me know if this solution works for your use-case. If not, maybe you could explain your use-case a bit better?

**Comment by dzmitry-lahoda** [comment]
presets are nice, will use these. so I was about automating this
1. export csv
2. send to customer

so flow to be:
1. ask customer email
2. allow him access any tags for any day automatically

**Comment by almarklein** [comment]
Ah, I initially thought you meant sharing tag names, but you mean sharing the summaries of time spent on specific tags, right? So instead of sending a report each month or so, you want to give a client direct access to a subset of tags.

**Comment by dzmitry-lahoda** [comment]
yes. and I can do both. send report. so still allow observing the ongoing process by a subset of tags. I am still in full control, I can give view access and take back. So I would prefer reclaiming be only future forward. I cannot prevent client see what he has already was seen. I can also set the specific start date of when he can start see. I cannot make start date smaller too. (Sorry for being too protocol - i am blockchain :) )

**Comment by almarklein** [comment]
This idea has crossed my mind, though it's not trivial - especially the auth part :)   Let's use this issue to track this idea, so others may also respond.

**Comment by dzmitry-lahoda** [comment]
not sure if oauth scopes allow for that. when scope is time range plus tags, but for me that look essential part of process so that counter party can trust app

**Comment by dzmitry-lahoda** [comment]
sharing should respect https://github.com/almarklein/timetagger/issues/128

**Comment by almarklein** [comment]
I have created a more general issue in #142, where this issue is one of the bulletpoints. Closing this in favor of the more general issue.
