### ISSUE TITLE
Alternative report groupings

### ISSUE THREAD

**Issue by Adam-D-Lewis** [almarklein/timetagger#120]
Timetagger is a nice, intuitive product that I enjoy using.  As a suggestion, perhaps there is a way to allow alternative report formats.  In my case I was hoping for a sum of hours grouped by date and tag across a date range which is similar to how I need to report it in Harvest (https://www.getharvest.com).

**Comment by almarklein** [comment]
Hi Adam, thanks for the suggestion! I like the idea of alternative groupings, and I can see how grouping by day would be useful!

**Comment by almarklein** [comment]
Just to be clear, because you mention "formats", do you also have suggestions for the export format (e.g. pdf vs csv)?

**Comment by Adam-D-Lewis** [comment]
No, pdf and csv have worked fine for me.

**Comment by almarklein** [comment]
This is now implemented, and live! 🚀  Please let me know whether this is what you meant.

**Comment by Adam-D-Lewis** [comment]
Yeah, that's definitely the idea I was going for, and does work for me. :+1: 

An additional improvement might add the ability to choose only certain tags to group by.  E.g. Let's say I was using tags to track which client I'm doing work for, and also using tags to track how much of my time I'm in meetings, programming, etc.  So I might have an entry like this `#client1 #meetings` and another `#client1 #programming`, but for the grouping option I may only want to group by `#client1`, `#client2`, and `#client3` and ignore the `#meetings`, `#programming`, and `#project-management` tags

**Comment by almarklein** [comment]
Your suggestion is already covered by an issue: #128. The plan right now is to first merge the color and target dialogs into a "tag config dialog". Then we add an option to mark tags as either primary or secondary. This info will then be used to sort the tags, and the report dialog can hide secondary tags.
