### ISSUE TITLE
🐞 Data loss during long text input with many tags

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#127]
Hi,

if I fill a time entry with many tags, this data will be lost. 
They will be deleted again after closing the dialog.

Example text:
#unterbrechung #govb-dev Testeintrag #kleinkram #kommunikation #fokus #unterbrechung #overhead-unternehmensplanung #overhead-personalmanagement #overhead-prozesse #overhead-prozessabwicklung #govb-dev #govb-test #ai #gu #wkis #wkobase #forbildung-aktiv #fortbildung-passiv #abwesend

Thanks
Chris

**Comment by GitHofi** [comment]
Normally I use about 2 tags per entry.

So why did I enter so many tags? ...
I wanted to set the colors for all the tags I currently plan to use. So I thought I'd just enter these tags to one event - then I could click on the individual tags and set the colors.

So ...
1) I do NOT need soooo many tags per entry 😉 
2) I too think the dialog should catch it when you reach the limit.
3) As a bonus, (as a feature request for the future) you could provide a way to enter and manage tags independent of concrete timelogs.

Thanks

**Comment by almarklein** [comment]
> as a feature request for the future) you could provide a way to enter and manage tags independent of concrete timelogs

Yeah, maybe as part of the "search & manage tags" dialog.
