### ISSUE TITLE
allow 61m

### ISSUE THREAD

**Issue by dzmitry-lahoda** [almarklein/timetagger#129]
as per iso duraiton standard, 61m is good time, so 0h 61m 01s = 1h 1m 1s. not 59m 1s, please allow for that

**Comment by GitHofi** [comment]
Hello, 
I am just a "normal" user of TimeTagger but curious 😉

- In what situation would you use this?
- For which cases would this be handy?

Thanks
Chris

**Comment by dzmitry-lahoda** [comment]
i report time passed, already done, it is easy to change minutes i field than type hours and minutes. overall i desktop version could have shortcut to report time.

**Comment by dzmitry-lahoda** [comment]
i am too lazy to input human hours.

**Comment by almarklein** [comment]
Out of curiosity, do you fill such numbers only in the duration field, or also the start/stop fields?

**Comment by dzmitry-lahoda** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/757125/151393367-57557a9f-ad5a-4316-bdf7-b0c6c3319d2d.png">
so I can type only 130m or 25h. so this should be very streamlined. may be big screen version could have separate button for this
