### ISSUE TITLE
Tags can be added multiple times

### ISSUE THREAD

**Issue by janharms** [almarklein/timetagger#13]
A tag can be added multiple times either manually or accidentally be search&replace.
<img width="491" alt="multiple tags" src="https://user-images.githubusercontent.com/995970/104497622-ee0d1b80-55da-11eb-9dca-cd1d152bcebf.png">

**Comment by almarklein** [comment]
When using the tag manager dialog, duplicates are resolved. You can still manually insert duplicate tags, but the dialog will show a warning.
