### ISSUE TITLE
💡 central configuration of tags

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#134]
I want to share some thoughts about the configuration of tags ...

Configuring tags via the overview view should definitely be kept. It certainly covers most of the situations where tags should be modified and is a very intuitive way to customize current tags. 👍 

But it still doesn't cover all cases ...
➀ what about tags, I don't see in the currently selected time range?
➁ what about tags, I want to use in the future but want to set time target, color etc. now?

**ad. ➀ ...**
Yes I could extend the time period for example to one year to see as much as possible of all the tags. But then a lot of tags are displayed and I have to find the right one in a big list.

A dialog that shows all tags would not be an optimal solution either - at least you would need a search function if you already use a lot of tags.

This leads us to the already existing dialog for searching and replacing tags ("Search and manage tags"). There was already the idea from Almar to extend this dialog. https://github.com/almarklein/timetagger/issues/127#issuecomment-1023538805

After some considerations (and discarding alternatives) 
I too think that this dialog would be quite suitable.

The problem I currently have with this dialog ...
- (A) the selection of a "search mode" AND the required hashtag in the search field seems counterintuitive and redundant to me
- (B) I need to know the exact tag name to find it.

So, to be able to efficiently manage a larger list of tags, I suggest:

**_ad. (A) not to have to type the hashtag_**
It is already defined by the "search mode" that you search for tags anyway
(see also ad. (B) below why)

**_ad. (B) to use the same auto-completion as when creating new tags_** 
(the autocomplete could also add the hashtag if you find that more intuitive)
This way you could enter only parts of a tag without having to know their exact name.

This way I could just type "cyber" hit enter and am done.
What I get from the autocompelte is something like #project-cyber2000-phase1

This would be an efficient way to find and manage tags without the need of a central listing of all tags.

**ad. (2)**
The third situation I was thinking about is to configure tags for which you don't have a time entry yet. This case is not yet covered BUT in my opinion is the least necessary. 

I suggest NOT to provide any extra functionality for this but to use a workaround. You can add a short time entry with these tags. If the duration of the entry is short - it should not matter. Not an elegant solution but although I already had this need myself, I could live well with the workaround.

Additional thoughts ...

No matter if the selection is done via the tags from the overview or via the dialog "search and manage tags" → I would always go to the same settings dialog for tags which then allows to :
 - enter a time target
 - set the color 
 - mark them as primary / secondary (✨ possibly future feature)
 - rename the tag
 - etc. 
This way we would have a consistent looking tag configuration dialog for each tag. 

I hope these thoughts make some sense 😉 and are helpful.

br
Chris

**Comment by almarklein** [comment]
Just commenting that in the new tag config dialogs we should add:
* A rename button.
* A button to see all records for that tag/tag combi.

This should go together with a refactoring of the search dialog.

**Comment by almarklein** [comment]
Some improvements have been made. The use-cases that are still left are:
* Being able to more easily search/select tags.
* Being able to open the tag dialog for a tag from some time ago.
* (maybe) being able to open the tag dialog for tags that don't exist yet.

I think we can get there by doing:
* Rename the search dialog just "Search".
* Still the same two modes.
* In tag-mode, there will be an autocompletion to help select known tags.
* There will be a button to open the tag-dialog for the currently selected tags.
* The "replacement" field can be removed - tags can be renamed from their dialog now.

**Comment by almarklein** [comment]
Closed by #210

<img width="794" alt="image" src="https://user-images.githubusercontent.com/3015475/172717545-a3db89d1-3f5e-4d60-98a7-63b6a8aa3a52.png">
