### ISSUE TITLE
💡 Forgotten activity change - "started earlier" creates overlap

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#135]
The situation is as follows:

There is a change of activity (e.g. I am being called) and I forget to change the activity in TT. If I then notice it, I can use the "started earlier" feature 👍 
BUT: with this I create an overlap because the end of the previous activity does not adjust.

My suggestion is...
that when "started earlier" is used, the end time of the previous activity also adjusts (at least if there would be an overlap otherwise)?

**Comment by almarklein** [comment]
At the very least, if you start a new record while the current one is still running, the current one should be stopped at the start time of the new record. That does not happen now, and I think we can consider that a bug.

As for starting a new activity while the previous record has already stopped, or editing the times of a stopped record, should it shift the neighboring records to prevent overlap? I think that makes sense. I'm trying to think of reasons why not.

One thing that does need some though it the previous record's stop time is pushed back beyond its start time.
