### ISSUE TITLE
💡 keyboard shortcut to resume last activity

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#136]
My suggestion:
Provide a keyboard shortcut for "resume".

My additional suggestion: 
Allow resume also when a current task is running (which is then ended automatically).

So it would simply be a combination of "stop" and "resume".

This would be helpful if you are working for the same customer on the same project - so the tags actually stay the same - but you start another activity and therefore want to change the activity description.

This way you could → just press the "resume key" and adjust the text.

Of course, you can already do that now. First stop the running task. Then open the last task. Then press resume. Those are just a few (unnecessary) steps more 😉 

Not a high priority request - but would come handy.

**Comment by almarklein** [comment]
This should be relatively easy to do with a shortcut. This feels like an alternative way to start a new record, so maybe Shift+S.
