### ISSUE TITLE
💡 presets for keyboard lovers

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#137]
I have the following suggestion regarding presets....

Presets for single tags are useful for people who prefer to use the mouse rather than typing. I am not one of those people and prefer typing 😉 . 

That means for me the preset list would be interesting for typical tag combinations I use often. But since I like to type I don't use this possibility. (The preset can currently only be selected with the mouse).

My suggestion would be ...
when typing and creating hashtags to not only show hits on individual hashtags, but also show hits from the preset list. The autocomplete should then apply the tag combination.

This would also allow users who prefer to work with the keyboard to use the preset list effectively without having to constantly switch to the mouse.

**Comment by almarklein** [comment]
I totally agree that presets should be more accessible via the keyboard. Some options:

* Adding them to the autocompletion list.
* Being able to toggle the autocomp between single-tags and presets.
* Numbering the presets, so you can just hit e.g. `ctrl+1`.

Keyboard shortcuts are a bit tricky here; you're in a text input, so a modifier key like Ctrl is needed.

**Comment by GitHofi** [comment]
I vote for option 1 → adding them to the autocompletion list. 👍 
I would start without a possibility to toggle between single-tags and presets (I don't think I would need that) and see how it does in real life.

**Comment by almarklein** [comment]
This is now implemented and deployed. I'm curious how people with large amounts of presets like this.
