### ISSUE TITLE
A tag edit dialog

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#139]
Related issues: #134, #128

We now have a dialog to set the color for a tag, and another to set the target. We should merge that into one dialog where a tag can be managed:

* set color
* set target
* set as primary / secondary (if we implement this)

The below needs more thought, as that replaces some functionality of the search tags dialog:

* search for records that use this tag.
* rename the tag.

**Comment by GitHofi** [comment]
A quite simple variant would be to combine the already existing dialogues.
Basically, the question for me would be whether it would be better to pack all settings into 1 dialogue, or whether you usually only want to set 1 action (rename, target, colour, priority)?

You could then adapt the "Search and manage tags" dialogue in one of the two ways as shown in the screenshot.
<img width="400" alt="TT_Settings_1button" src="https://user-images.githubusercontent.com/12327228/151928232-781aacaf-e3cb-4844-ac93-f201c9ef5bc4.png">
<img width="400" alt="TT_settings_4buttons" src="https://user-images.githubusercontent.com/12327228/151928265-2caaf395-41c1-461a-aff6-139ac64d8ea4.png">

Depending on the variant, you get into 1 setting or can select from 4 specific settings.

If you click on a tag in the overview, you have the same design choice: either 1 settings button or 4 individual ones.

I would tend to display 4 individual buttons. I think most of the time, I want to change a specific aspect for one or more tags. If I want to change several aspects, I could just press the relevant buttons one after the other. As long as the selection (affected tags) remains the same, this should not be a problem.

Additional thought:
If you adjust the search for tags in such a way, that you can search for tag parts (e.g. all tags that contain "process" (see similar considerations at https://github.com/almarklein/timetagger/issues/134 ), you would have a quite flexible and powerful solution.

**Comment by almarklein** [comment]
Thanks for the suggestion. I'm more leaning towards a single button leading to a dialog with multiple tag-options myself. I think it feels more consistent, and the UI will be a bit cleaner that way.

> If you adjust the search for tags in such a way, that you can search for tag parts (e.g. all tags that contain "process" (see similar considerations at #134 ),

I thought of that as well. That way you can actually search for tags. Although adding autocompletion to this dialog would solve that too, I suppose.

**Comment by GitHofi** [comment]
Yes, a single button would also be ok from my point of view - I don't really have a preferred variant.

As you can see from the picture, I am not a UI designer 😉. But this is roughly how I imagine a common dialogue (low effort).
<img width="395" alt="2022_0201_1157_01" src="https://user-images.githubusercontent.com/12327228/151960616-750de635-81b3-43db-8c87-327f741a1740.png">

The order of the areas should probably be arranged differently - perhaps one below the other.

Such a dialogue could then be opened from the "Search and manage" dialogue as well as from a tag (opened from the Overview).

**Comment by almarklein** [comment]
I was about to start on merging the color and target dialogs when I realized that ... colors are per-tag, but targets are per tag-combination. I need to think this over.
