### ISSUE TITLE
Add hint about how to select multiple tags

### ISSUE THREAD

**Issue by janharms** [almarklein/timetagger#14]
When generating a report it would be useful downright necessary to be able to select multiple tags.
<img width="351" alt="multiple tags in report" src="https://user-images.githubusercontent.com/995970/104497776-27de2200-55db-11eb-90f8-811b71b41829.png">

**Comment by almarklein** [comment]
Thanks! You can, actually, by holding shift/control while selecting a next tag. But I agree that it's not obvious at all. This feature should be "documented" in some way, perhaps with a subtle text somewhere once 1 tag is selected.

**Comment by janharms** [comment]
Feature works nicely. A hint would be sensible.
Regards

**Comment by almarklein** [comment]
I'm keeping this open to track the issue until I've added the hint.

**Comment by almarklein** [comment]
![image](https://user-images.githubusercontent.com/3015475/104743670-3ef05180-574c-11eb-8b49-5729c0978913.png)
