### ISSUE TITLE
Make it more obvious when a record is running

### ISSUE THREAD

**Issue by eldelacajita** [almarklein/timetagger#159]
This is just an idea for a very small but helpful enhancement: just make it more visible when a record is running.

A simple way of doing this: Changing the colors of the single "Record" button to white on green, and the "Stop" button to white on red. The "secondary" record button (the one that appears beside the stop button) could be kept as is.

A complementary change could be to also change the background color of the active/running record on the timeline.

**Comment by ccamara** [comment]
+1 to this feature. A switch on/off (stop doesn't make sense if no time is being tracked and conversely play when is already tracking) could also be considered

**Comment by GitHofi** [comment]
Thank you for raising the point. Especially the desire to quickly see which record is actually being recorded would be helpful. When there are many alternating activities, I'm not always sure if the current recording is for the right activity.

I had the idea of highlighting the current recording in the overview or even displaying which activity is currently being recorded at the top of the header.

**Comment by eldelacajita** [comment]
I'd just use some more static, subtle hints. I usually have TimeTagger open on my secondary screen, and I wouldn't want blinking or flashing things, apart from the blinking dot, which is great as it is.

**Comment by GitHofi** [comment]
> The current activity has a thicker outline
@eldelacajita 
Thanks, I wasn't sure about the thicker outline - it really can be called "subtle" 😉 
The difference is so small that I wasn't sure if I was only imagining it.

I wouldn't mind if the frame was highlighted more noticeably, e.g. in yellow like the button.
