### ISSUE TITLE
Restore being able to select presets with the mouse

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#161]
Presets are now shown in the autocompletion, which is great for users on a keyboard, but for mobile users and users who have a tendency to use the mouse, this might feel like a step back.

We need (again) a button to show the list of presets. Maybe another button to show recent tags. Or ... a button that shows both, like what is shown now when you enter the first "#".

**Comment by ouuan** [comment]
Actually, this can be as simple as adding a button to input a `#`.
