### ISSUE TITLE
Able to sync between devices with the self-hosted version?

### ISSUE THREAD

**Issue by Joshfindit** [almarklein/timetagger#17]
I see references to sync in the code here, but the pricing section seems to imply that sync is paid only.

**Comment by almarklein** [comment]
Good point, that is a bit confusing. I made the assumption that most people running it themselves would run on localhost, in which case there is no syncing. However, if you self-host on a server, syncing works fine. Thou you'd have to arrange authentication. I will remove that line to avoid confusion.

**Comment by Joshfindit** [comment]
That being the case, I’d actually suggest keeping it but giving it a checkmark. Device sync is a huge bonus and not supported in many things.

**Comment by almarklein** [comment]
It's mentioned in the highlighted features at "take it anywhere". I also clarified a bit in the FAQ.
