### ISSUE TITLE
Description spelling and Grammarly

### ISSUE THREAD

**Issue by dzmitry-lahoda** [almarklein/timetagger#175]
1. Install Grammarly extensions to Brave
2. Start Record -> Description
3. Write nonsense like asdajdqw
Expected: Grammarly will suggest error
Actual: Grammarly does not check the Description element (seems like HTML tags do not trigger text analysis)
Notes: Open Tag Presets. And see that Grammarly is presented and recommends fixes to text. Also, the GitHub issue I type is also analyzed.
Why: I want my customer to be clear on what I am doing and believe he hired professional:)  Spelling is important here.

**Comment by almarklein** [comment]
Now live.

**Comment by ouuan** [comment]
Grammarly only works in `<textarea>`, not in `<input>`.

**Comment by almarklein** [comment]
Mmm, so we have spell checking, but not from grammarly. Is there a way to make Grammarly work for (this) `<input>` as well?

Otherwise I'm not so sure what to do, because I really feel the description should be a one-liner.
