### ISSUE TITLE
"Server is starting up" hangs forever when initiating with --bind=localhost:3000

### ISSUE THREAD

**Issue by dvdmrn** [almarklein/timetagger#186]
I setup timetagger on a home server following: https://timetagger.app/articles/selfhost/

I need to serve timetagger on another port, since localhost is occupied, so I run it as: `python run.py --bind=localhost:3000`.
When this happens it goes:

```
[INFO 2022-03-18 14:26:56] Collected 11 assets from /home/pi/Dev/timetagger/timetagger/common/.
[INFO 2022-03-18 14:26:56] Compiled pscript from dialogs.py
[INFO 2022-03-18 14:26:56] Compiled pscript from dt.py
[INFO 2022-03-18 14:26:57] Compiled pscript from front.py
[INFO 2022-03-18 14:26:57] Compiled pscript from stores.py
[INFO 2022-03-18 14:26:57] Compiled pscript from tools.py
[INFO 2022-03-18 14:26:57] Compiled pscript from utils.py
[INFO 2022-03-18 14:26:57] Collected 13 assets from /home/pi/Dev/timetagger/timetagger/app/.
[INFO 2022-03-18 14:26:57] Collected 25 assets from /home/pi/Dev/timetagger/timetagger/images/.
[INFO 2022-03-18 14:26:57] Collected 4 assets from /home/pi/Dev/timetagger/timetagger/pages/.
[INFO 2022-03-18 14:26:59] Server is starting up
```

But just hangs there forever, and going to localhost:3000 / pi.ip.address:3000 gives an "error connection refused"/"unable to connect" error in the browser.

When I run simply `python3 run.py` I get:
```
[INFO 2022-03-18 14:33:10] Collected 11 assets from /home/pi/Dev/timetagger/timetagger/common/.
[INFO 2022-03-18 14:33:11] Compiled pscript from dialogs.py
[INFO 2022-03-18 14:33:11] Compiled pscript from dt.py
[INFO 2022-03-18 14:33:11] Compiled pscript from front.py
[INFO 2022-03-18 14:33:11] Compiled pscript from stores.py
[INFO 2022-03-18 14:33:11] Compiled pscript from tools.py
[INFO 2022-03-18 14:33:12] Compiled pscript from utils.py
[INFO 2022-03-18 14:33:12] Collected 13 assets from /home/pi/Dev/timetagger/timetagger/app/.
[INFO 2022-03-18 14:33:12] Collected 25 assets from /home/pi/Dev/timetagger/timetagger/images/.
[INFO 2022-03-18 14:33:12] Collected 4 assets from /home/pi/Dev/timetagger/timetagger/pages/.
[INFO 2022-03-18 14:33:13] Server is starting up
ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
[INFO 2022-03-18 14:33:13] Server is shutting down
```
which is expected, since 0.0.0.0:80 is currently occupied for me by another service.

How can I get this to run on a different port?

**Comment by almarklein** [comment]
> But just hangs there forever

That is the last message on a successful startup, so it's likely running, not hanging.

> [...] gives an "error connection refused"/"unable to connect" error in the browser.

You could try `0.0.0.0:3000`, that should at least open the port to access from other machines.

You could also check the firewall, maybe it's blocking port 3000.

**Comment by dvdmrn** [comment]
Ahh when I ran `python run.py --bind=0.0.0.0:3000` instead of `python run.py --bind=localhost:3000` it did the trick! Thanks! :)
