### ISSUE TITLE
Ability to hide tags on "this week" "this month" views

### ISSUE THREAD

**Issue by EncroachGradually** [almarklein/timetagger#189]
To explain the use case a bit more I currently tag #productive #procrastination #deepwork #shallow when using the this week/last week etc it'd be useful to be able to remove them to get visual ratios, I mark procrastination in red and productive in green and seeing just the divide between those two is helpful for quickly visualising time spent

**Comment by almarklein** [comment]
Thanks for the suggestion!

Are the tags that you'd like to hide always the same? Or are you looking more for a way to compare a specific subset of tags? 

This sounds a wee bit like #128, and even more like #125. Could you please explain how what you mean is similar/different from your ideas?

**Comment by EncroachGradually** [comment]
#128 Would fit perfectly since it would add the ability to "refine" the report and only leave certain tags looking at your solutions [here](https://github.com/almarklein/timetagger/issues/128#issuecomment-1022706753) for my use case option 1 or three would work perhaps the way you do it through (1) could be similar to presets so the end user can just easily add which tags they don't/do want to be included in reports/timeline, I'll leave this open but feel free to close it since it's basically a duplicate of #128 but worded differently essentially when using the timeline view that shows each day with color chunks representing different tags I want to be able to have that not include certain tags so I can easily see time spent doing a vs b - hope this clears it up a bit

**Comment by almarklein** [comment]
Thanks for the clarification! Note that #128 talks about the report (as seen via the report dialog), not the timeline view. But I think it makes sense to apply the same filtering to the timeline. I will add a note in #188 (which implements #128).
