### ISSUE TITLE
Add docker-compose.yml

### ISSUE THREAD

**Issue by sudoWiz** [almarklein/timetagger#190]
This project is great, but I won't self-host this until a docker-compose file becomes available. All of my current self-hosted apps have docker-compose files for easy configuration, backup, and migration.

I believe that the needed information to put together my own docker-compose.yml might be available, but I do not have the experience to do this myself, or the confidence that I could do it right.

Bottom-line is this: no matter how easy the current self-hosting method is, I want all of my apps to be managed the same way, and I don't think I'm the only one who operates like this. I would be happy to help however I can, and I plan to make a donation to the project if this feature becomes available.

**Comment by almarklein** [comment]
Thanks for the feedback!

There are currently a few improvements that I'm working on. After that I plan to improve the self-hosting workflow.

**Comment by almarklein** [comment]
> This project is great, but I won't self-host this until a docker-compose file becomes available. 

It's [available](https://github.com/almarklein/timetagger/blob/main/deploy/docker-compose.yml)! 😄
