### ISSUE TITLE
importerror for config?

### ISSUE THREAD

**Issue by chrisco23** [almarklein/timetagger#191]
Hi,

I'm sure this is probably my very limited python knowledge, but I did the pipinstall, copied run.py as 'timetagger.py', and did 'python timetagger.py' but I get:

`ImportError: cannot import name 'config' from partially initialized module 'timetagger' (most likely due to a circular import)`

because pip install appeared to put things here, I'm running from ~/.local/lib/python3.10/site-packages/timetagger

**Comment by almarklein** [comment]
> copied run.py as 'timetagger.py'

There's the cause, I think :)  - Since your script has the same name as the library, Python tries to import your script instead, resulting in a circular import.

**Comment by chrisco23** [comment]
Oh, haha, that was indeed that problem.

Although, I did hit a new snag then.  I got

`ERROR:    [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied`

So I tried with sudo and I got

```
  File "/home/mylinuxuser/.local/lib/python3.10/site-packages/timetagger/tt.py", line 11, in <module>
    import asgineer
ModuleNotFoundError: No module named 'asgineer'
```

So I sort of guessed here but got:

$ pip install asgineer
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: asgineer in /home/mylinuxengineer/.local/lib/python3.10/site-packages (0.8.1)

Something wrong with my python installation??

**Comment by almarklein** [comment]
> `('0.0.0.0', 80): permission denied`

That's probably your filewall preventing you from opening a public port on port 80. I think you can change the port to e.g. 8080. Or you can configure the firewall.

I guess that `sudo` should also work. The thing is - and I'm not 100% sure how this works exactly - that the sudo user has a different place that python packages are installed. So you'll want to do something like `sudo python -m pip install timetagger` to fix that.

**Comment by chrisco23** [comment]
Yes and 8080 works fine!

Thanks again.
