### ISSUE TITLE
Popup outside the visible area creates "flickering"

### ISSUE THREAD

**Issue by GitHofi** [almarklein/timetagger#204]
Small glitch with windows that are not very wide (mobile layout on desktop).

If you move the mouse pointer over the entries in the timeline, a pop-up appears with the message "(click to edit)". However, if the window is in "mobile layout", the pop-up appears outside the visible area on the right.
I wouldn't really care, because I don't need the popup → BUT: this popup also causes the scrollbars to be displayed and this constantly creates an unattractive flickering.

Thanks

**Comment by almarklein** [comment]
I can indeed reproduce this. Thanks!
