### ISSUE TITLE
time looks  different on android and desktop

### ISSUE THREAD

**Issue by gerroon** [almarklein/timetagger#206]
Hi

I am using the self-hosted python as is and I disabled the localhost check. The app seems to function pretty well on desktop and Android however the recorded times do not match. 

I started a test time recording. It shows 4 mins on desktop and 1:30 on Android. For some reason Android page is always 2 mins 30 secs behind. When the record is below a minute it shows negative minutes on Android until it passes above 0. I actually did a bunch of tests before posting this report.

I tested Firefox and Chromium on Android and the results were the same so this does not seem to be a mobile browser issue.

Bear in mind that both devices are using the same wifi and  the same time zones.

Desktop: Win 11
Android: Lineage OS 18.1

**Comment by almarklein** [comment]
The TimeTagger app uses the browser's time module, which uses the system's internal clock. Could it be that your devices differ in time a few minutes?

**Comment by gerroon** [comment]
That makes sense. I assumed that there was a central time keeping.

**Comment by almarklein** [comment]
Yeah. I guess we could say that for the app to work well on multiple devices, it's important that these devices have a clock that is not lagging or running ahead to much.

For the record, it should work fine if your devices use a different timezone or summertime/wintertime, whatever. All times are stored as Unix time stamps.
