### ISSUE TITLE
Editing end-time and pressing enter will not apply that end time

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#217]
Looks like the end-time is only applied when the input field loses focus (`onchanged`). See https://github.com/almarklein/timetagger/issues/216#issuecomment-1154825669 for details.

cc @sergeolkhovik

**Comment by sergeolkhovik** [comment]
BTW the same problem happens if I edit finished task and want to change the start time, do modifications and hit 'enter' without leaving that field.

**Comment by almarklein** [comment]
Fixed, and the app has been updated.
