### ISSUE TITLE
Permission Issue on Mac running docker-compose with Rancher

### ISSUE THREAD

**Issue by ChadDa3mon** [almarklein/timetagger#221]
Odd issue while using your default docker-compose, running on the latest version of MacOS

```
$ docker-compose up -d
[+] Running 1/1
 ⠿ timetagger Pulled                                                                                                                                               5.9s
[+] Running 1/2
 ⠿ Network timetagger_default         Created                                                                                                                      0.0s
 ⠿ Container timetagger-timetagger-1  Starting                                                                                                                     0.4s
Error response from daemon: error while creating mount source path '/Users/Me/scripts/TimeTagger/_timetagger': chown /Users/Me/scripts/TimeTagger/_timetagger: permission denied
```

I ran ```chmod 777 ~/TimeTagger/_timetagger``` and things fired up fine.

**Comment by almarklein** [comment]
Could it be that Docker does not have the right user/access for some reason? It looks like the error occurs while preparing the mounted volume. I'm on a Mac as well, and I cannot reproduce the error.

**Comment by ChadDa3mon** [comment]
It could be, now that you mention it, I'm running rancher (not docker desktop) but it usually doesn't matter. I'm happy to say it's just my issue if you can't reproduce it.

**Comment by almarklein** [comment]
> I ran chmod 777 ~/TimeTagger/_timetagger and things fired up fine.

Do you mean with this that after running `chmod` it worked without problems?

**Comment by almarklein** [comment]
`chmod 775` should be sufficient as there is no need to execute files - only storage.

**Comment by ChadDa3mon** [comment]
Correct, it worked without problems, I'm trying it out now :)

As for 777, I just wanted to verify if it was a permissions issue or not, I'm not too concerned with permissions on my local device.
