### ISSUE TITLE
More secure authentication

### ISSUE THREAD

**Issue by almarklein** [almarklein/timetagger#222]
The use of SHA1 to hash passwords might be a security risk if users don't thread the hash like a secret. See e.g. this discussion on Reddit: https://www.reddit.com/r/selfhosted/comments/vhgo7x

Options for improving this:
* Using SHA256 or e.g. bcrypt.
* Salting the password.
* The request should put the credentials in the header, not the url (to prevent it from entering into logs).

Note that as long as you do not share the hashed password, there is no problem. And even if you do an attacker must do a considerable amount of work to find a collision.

**Comment by Cyborger** [comment]
The biggest security issue right now isn't the fact that the attacker might attempt to find a collision themselves but more that they would just match the hash with a rainbow table.

Most users are known to use very common passwords and reuse them everywhere even for their banking account so when the database or password hash will leak by any mean, it will also be public forever and any attacker even in the future could crack the hash with much ease...

Except for testing and learning purposes, attempting to make a self-implementation of a secure password auth machanism isn't and will never be a great idea. If there isn't any alternative like Oauth2, please make use of the cryptography python module with it's key derivation functions and never tell the user about their hash as they should not be trusted to keep a secret.

**Comment by almarklein** [comment]
Thanks @Cyborger for the clarification.
