### ISSUE TITLE
In edit record windows, pulldown tag selection menu can not be closed by click blank area.

### ISSUE THREAD

**Issue by sulisu** [almarklein/timetagger#226]
Update to 22.6.4 from pypi yesterday.

In edit record windows, pulldown tag selection menu can not be closed by click blank area unless making some selection or clicking Cancel button.

**Comment by almarklein** [comment]
I can reproduce this. It seems to occur only when you activate the tag-selection-menu by clicking the button. If you activate it by typing "#", it works fine (which is why I hadn't spotted this issue yet).

This is likely another regression from #210, and seems somewhat related to #212.

**Comment by almarklein** [comment]
Thanks for the report! I'll try to fix this today or tomorrow. For the time being, note that you can also exit the dropdown using the escape key.

**Comment by almarklein** [comment]
Actually, the error was introduced in #211.

**Comment by almarklein** [comment]
Fixed. New version is on pypi. Will also deploy the new version.
