### ISSUE TITLE
Feature request: Change favicon when time is being tracked

### ISSUE THREAD

**Issue by fatflyingpigs** [almarklein/timetagger#233]
I find myself checking my timetagger tab more frequently than I need, to double check I am recoding my time. It would be nice if we could look at the tab's favicon for visual feedback.

Personally I'd favor a red dot in the top, similar to this (though this is a 'notification' for discord): ![image](https://user-images.githubusercontent.com/2653682/179454312-1290042f-ccdb-4b25-b994-69ebfca4de2b.png)

**Comment by almarklein** [comment]
Good idea!

**Comment by almarklein** [comment]
Might be good to make it more clear somehow that there are pending changes that are not yet sent to the server. This might avoid #232

**Comment by almarklein** [comment]
Done!
