### ISSUE TITLE
Improved tag search

### ISSUE THREAD

**Issue by jiri** [almarklein/timetagger#235]
I'd love to be able to search for entries that **don't** have a tag. I use a tag to track time that has been billed, so being able to filter billed time out would help me to not go crazy :)

**Comment by almarklein** [comment]
Do you mean in the "Search records and tags" dialog? It would indeed make sense to be able to use `#untagged` to search for untagged entries.

**Comment by jiri** [comment]
I'm sorry, I'll try to rephrase this more clearly. I want to filter certain tags out, so I'd like to search for "tags with the `#project` tag but NOT the `#billed` tag". Basically just perform completely standard set operations on the tags :)

**Comment by almarklein** [comment]
Thanks for the clarification. A simple "query language" like that seems reasonable!

**Comment by almarklein** [comment]
Done! I opted for prepending tags/words with "!".
