### ISSUE TITLE
Scaling/size issue

### ISSUE THREAD

**Issue by jjj133** [almarklein/timetagger#241]
On the newest version of Chrome on Kubuntu, and also Windows 11 on Chrome and Edge, I cannot see the full time. It cuts it off after 3.5 digits. Example: for 11:00:00 I only see 11:0 and half of the next 0.

Edit to add: I've tried scaling in windows and well as scaling in the browser (Ctrl -/+) to no avail. It stays the same no matter what I do.

**Comment by almarklein** [comment]
Thanks for reporting this!

I cannot replicate this problem on latest Chrome (104.0.5112.101) myself, though I only tried on MacOS so far. Could you please specify the Chrome version, and a screenshot to illustrate the problem?

**Comment by almarklein** [comment]
I also tried to replicate on Windows 11 (both on Chrome and Edge). But I cannot detect any issues like this. Could you please describe what number is being cut off (e.g. is it in the timeline or in the report dialog)?  A screenshot would be great to help see the problem :)

**Comment by almarklein** [comment]
Closing this now, because there is not much I can do if I cannot replicate it and/or know where the issue occurs. Will reopen if more info is available.
