### ISSUE TITLE
Shortcut bug on Safari  (iPad)

### ISSUE THREAD

**Issue by Z3nto** [almarklein/timetagger#243]
I use an iPad with Keyboard to use timetagger. The keyboard shortcuts only work after reloading the page.
After i.e. I start a record they no longer work.

I've noticed that the focus remains on `<input type="text">`. When I delete this specific element, focus jumps to `<body>` and shortcuts work again.

**Comment by almarklein** [comment]
Could you please be a bit more precise. What shortcut does not work in what situation? Or maybe explain the steps that lead to this unwanted behavior in more detail?

TimeTagger does behave slightly different when it expects a keyboard to be present, but the test for this is not very reliable - you cannot ask the browser whether a keyboard is present, so it mainly checks the screen size. This might partly explain the behavior. Maybe an extra focus step is needed on "small devices" to make shortcuts work ...

**Comment by Z3nto** [comment]
All shortcuts that are listed in settings are affected. Let's use the shortcut "S - Start the timer" in this example.

- Load the page
- Press S
- Dialog to start a records opens
- Fill dialog and close it again (i.e. with Enter or press on Start)
- Press S again -> Nothing happens -> Focus remains on `<input type="text">`
- Also any other Shortcuts (also the arrows) is not working 

Hope this describes it better

**Comment by almarklein** [comment]
Thanks! Odd that this happens. Perhaps the focus should explicitly set back to canvas/body when a dialog closes. Will have a look.
