### ISSUE TITLE
Not using timezone supplied by system

### ISSUE THREAD

**Issue by sschwetz** [almarklein/timetagger#254]
I am running the docker version of timetagger which is perfect for my uses. I have noticed and not been able to resolve the timezone as showing incorrect, it shows as UTC+1/GMT+11 summertime, but this should be UTC+10/GMT+11 summertime

<img width="277" alt="2022-09-13_21-48-06" src="https://user-images.githubusercontent.com/19428602/189893886-241ed1b0-9253-4a05-833f-e23cad2db8d1.png">

**Comment by almarklein** [comment]
I can reproduce this bug.

**Comment by almarklein** [comment]
Another thing. From what I can find, UTC and GTM should show the same time; GMT does not do summertime. I guess I was misinformed about this when I wrote that code.

**Comment by almarklein** [comment]
Thanks for reporting!
