### ISSUE TITLE
Docker Build for ARM64

### ISSUE THREAD

**Issue by tderflinger** [almarklein/timetagger#257]
Hello!

I like timetagger a lot and use it on an ARM64 machine. Currently, I am starting the application from source manually, but I would like to run it as a docker container.

Unfortunately, I cannot start the Docker container on my ARM machine because there is only a version for Intel architecture, I assume.

Would it be possible to also release a Docker image for ARM machines? That would really also help people using Raspberry Pis and other ARM machines.

I think there is a Docker command `buildx` for creating images for other architectures.

Thanks,
-Thomas

**Comment by almarklein** [comment]
Hi, @dorianim contributed the GH action to build the Docker image: https://github.com/almarklein/timetagger/blob/main/.github/workflows/dockerimage.yml

I presume it would be possible to make it build an image for ARM too, but that may depend on https://github.com/docker/build-push-action

**Comment by dorianim** [comment]
Yes, as long as the base image has an arm version available, it should be really straight forward :) see here for an example: https://github.com/dorianim/mrbs-docker/blob/main/.github/workflows/release.yml#L29

**Comment by maresmar** [comment]
The support for ARM images was merged in #365, so this could be probably resolved :smile:
