### ISSUE TITLE
import results in 1970s

### ISSUE THREAD

**Issue by kuschel** [almarklein/timetagger#276]
I tried to import data from a custom format (Baralga). I renamed the colums for project, start and stop time and changed german date format dd.mm.yyyy to yyyy-mm-dd. But start and stop in format hh:mm won't be accepted. If I change hour format from hh:mm to hh.mm import works. But I get some loose entrys in January 1st in 1970. What went wrong?

For example here is a line to test import:

project;date;start;stop
doings;2022-10-24;08:37;11:06

**Comment by almarklein** [comment]
Right, the import mechanism did not support the combinaton of a date with start and stop times (often it's a date, start time, and a duration). I improved the logic in #277. I think it should be possible to import the data as-is (e.g. the date format that you mentioned should also be supported).

> If I change hour format from hh:mm to hh.mm import works. But I get some loose entrys in January 1st in 1970. What went wrong?

Thanks for mentioning this. Gets a bit detailed, but what happens is that when you write it as hh.mm, then it gets interpreted as a float, and the import logic would consider it a unix timestamp, which is basically a number that counts the seconds from 01-01-1970. In #277 I now detect this to prevent this. And both hh:mm and hh.mm are supported now. 

Note that #277 is merged, but has not been deployed yet. I will comment here when it is.

**Comment by almarklein** [comment]
Released and deployed 🚀

**Comment by kuschel** [comment]
Works great in version 22.10.1.
I had to change the code page from ANSI to UTF-8 to get the special characters computed (e. g. "ü", "ß"...), but then the data was imported successfully.
Well done. Thank you very much :)

**Comment by almarklein** [comment]
Glad to hear!
