### ISSUE TITLE
export date to local (dd/mm/yyyy) but import expect mm/dd/yyyy

### ISSUE THREAD

**Issue by gitUser000** [almarklein/timetagger#285]
import/export bug observed on :  french win10 OS with python 3.6.9

export set date to day/month/year as expected by local settings
BUT import always expect  : month/day/year 

To test : re-import exported record : failed

Resolved by 
export to csv 
in csv : search  (\d\d/\d\d) and replaced by \2/\1
import from csv : passed

**Comment by gitUser000** [comment]
Sorry about this : problem came because of several copy/paste across notepad++ and excel (which change time format !)

Not a timetagger  bug.

Thanks for this tool...

**Comment by almarklein** [comment]
😄  Thanks for trying to help improve TimeTagger though 👍
