### ISSUE TITLE
Buttons not clickable in all locations

### ISSUE THREAD

**Issue by Z3nto** [almarklein/timetagger#286]
Hi @almarklein ,
the issue from #242 is still present (or again?) in  Version 22.10.1. It's not possible to press the buttons on the bottom end of its area. The "v" Button is only clickable on the top area.
Reproduced in Chrome, Firefox, Desktop app and Safari. Can you please have a look?

Here's the example image again from #242
![image](https://user-images.githubusercontent.com/22791287/202399876-746c37ab-eed2-4aff-b199-8686c2131c3e.png)

**Comment by almarklein** [comment]
I can indeed reproduce this. Odd. I'll have a look at what causes this ...
