### ISSUE TITLE
small "cosmetic" bug on "search and records"

### ISSUE THREAD

**Issue by gitUser000** [almarklein/timetagger#289]
Hi, just a small "cosmetic bug"

When you begin to search for tag/strings : 
strings immediately go from 0 to 1  (normal because there is always at least 1 letter found) but when you have finished to enter word(s) and the nothing found : string stay to 1 
Of course no records display so not a big bug (but could be confusing :-) )
 
![22-11-21_15-04-42](https://user-images.githubusercontent.com/112063540/203075028-035ace00-9f5a-46a3-90eb-02ba52fbd859.jpg)

**Comment by almarklein** [comment]
Thanks! Improved the search dialog. A new release is available!

**Comment by gitUser000** [comment]
Update done : Great 
Thanks for your work....
