### ISSUE TITLE
Bug : Start record dialog box not set when selecting String and not #tag (v 22.11.1) 

### ISSUE THREAD

**Issue by gitUser000** [almarklein/timetagger#295]
Small bug observed on v22.11.1 
 
When opening start record dialog box (tags: #untagged when opening)

When inserting "string" or #tag we got any matching descriptions as previous version, but the problem came from filling the input-box with dropdown-values

- IF we are using ONLY description strings : FAILED to fill input-box (input-box still get empty)
- IF we are using some #tag(s)  : FILLING input-box is OK

**Comment by almarklein** [comment]
I'm either not able to reproduce this, or I don't understand what you're doing. So let's take this step by step.

* I opened the [demo](https://timetagger.app/app/demo) to have somewhat reproducable records.
* I open the play button - the record dialog appears.
* In the description field, I type "some" - the autocompletion pops up, showing several options.
* I hit tab to select the first. Or I click on it. The description field now has this value.

Does this work differently on your machine? If so, what OS and browser are you using?

**Comment by gitUser000** [comment]
I investigate a bit more, so following yours steps :
- I open the play button - the record dialog appears.
- In the description field, I type "some" - the autocompletion pops up, showing several options.
- I hit tab to select the first. Or I click on it. The description field now has this value.
=>
IF i use TAB and Arrows to select one options : NO PROBLEM 
The "bug" only appears when using record with mouse.. AND (here is the deal :-) ) only on some records ...

On the screenshot : 
- using TAB (and arrows) to select ANY records to fully enter description field is OK
- first line will be "ok" to fully enter description field if we click on it 
- second line won't be able to enter full description if we click on it (but again : TAB is ok so not a big deal ...)
Its seems related to presence of double quotes in the record's description 

in case of : WIN10 Pro, Firefox 102.4.0esr

![22-11-23_08-09-47](https://user-images.githubusercontent.com/112063540/203490396-b7b7dd99-e818-4556-b7ec-5854889474ea.png)

**Comment by almarklein** [comment]
This was a sloppy bug. Thanks for reporting it! ❤️ 

It is now fixed, a new release is made, and the new app is deployed. 🚀
