### ISSUE TITLE
description entry with tag presets deletes already entered text

### ISSUE THREAD

**Issue by Floehe** [almarklein/timetagger#301]
Hi,
currently in version 22.11.2 (this is where it started), and also in 22.11.3, when starting a new task, and entering some text in the description field: when I type "##" to search for saved task presets and choose an entry from the dropdown, the previously entered text in the description field is deleted and replaced by the tag from the list. ;)

In earlier versions, the tag was added to the description text.

Could you please have a look at this?

Thx,
Florian

**Comment by almarklein** [comment]
Hi Florian, this behavior is intended. The expectation is that for single tags, you typically add or insert then into the description, but for presets you usually start off with them, and then maybe add some text. From your reaction I feel that my assumption may not hold for everyone :)

The idea of replacing the whole text is that e.g. you can select a preset, and then realize you need another and select that instead. 

I'm open to reconsidering this behavior. Would you mind explaining your workflow a bit more?

**Comment by Floehe** [comment]
Hi Almar,

Usually I am noting in the description field, what task I just started or what I have just finished. After enter a description on what I did, I want to categorize this task with tags. Therefore I created tag presets like "#monitoring #logging" which I access by pressing "##" after entering the description. 
That was possible until the version I described above. But it will also be fine for me to turn that around and start by choosing a tag preset and then entering the description. I just wondered why it had changed :)

BR, Florian

**Comment by almarklein** [comment]
I see. I can see how it can be annoying that the whole text is removed. I'll play with the behavior and see how this can be improved without things becoming too magical.

**Comment by Floehe** [comment]
thank you very much, just let me know of the outcome :)

**Comment by martin-braun** [comment]
@almarklein here is my additional suggestion about this problem. If you start by selecting a preset, you most likely want to add something else. I.e. preset is `#project1 #client2`, I'd want a space to be inserted after it. I also want to jump into the text box (focus) right away. If the text box already has text, the preset should be appended with a space prepended. This way would allow anyone to insert tag presets before or after neatly without typing unnecessary spaces etc.

Flowchart: 

```mermaid
flowchart
A[Insert Preset `#project1 #client2`] --> B{Text Box contains text?}
B -->|Yes| D[Append Text Box ` #project1 #client2`] --> F
B -->|No| E[Set Text Box value to `#project1 #client2 `] --> F
F[Focus Text Box]
```

**Comment by almarklein** [comment]
The behavior has been refactored and should feel more natural now!

**Comment by martin-braun** [comment]
@almarklein Okay, finally had time to upgrade. The inserting works great when you've typed something in, (sorta to give a hash tag at the very end after putting in the description). However, when I choose to insert first the tags and then the description, it will not insert a space character and auto-focus my text box, so I continue writing.

**Comment by almarklein** [comment]
>  it will not insert a space character and auto-focus my text box

I can indeed reproduce this if I insert tags/presets via the button. Tracking in #335

**Comment by almarklein** [comment]
Thanks for the update!
