### ISSUE TITLE
Adjust CSV report so that Excel can import it

### ISSUE THREAD

**Issue by gitUser000** [almarklein/timetagger#302]
Hi, 
default separator when saving report as csv is comma but if comma was inserted in description it could mess the records exporting...

As copy table (tab separator) has not same level details, it will be nice to be able to select a new separator ( <tab>,  <|>,  <;>,  .......) when csv exporting...

Thanks again for your works !!!

**Comment by almarklein** [comment]
>  but if comma was inserted in description it could mess the records exporting...

This is not true. Descriptions are put in double quotes to prevent this. This is the standardized way to allow commas in fields. While LibreOffice and Google Sheets handle this perfectly fine, I just checked and MacOS Numbers also splits on commas inside quotes. This means that Numbers does not honor the standard 🤷.

The problem with allowing a different separator is that this separator can *also* be present in the description, so it would not really solve the problem.

The fact that some apps don't follow the CSV standard as they import the data is annoying, but - bluntly put - not my problem.

I does seem though, that double-quotes inside the description are not doubled as they should be. Will leave this open to track that.

**Comment by gitUser000** [comment]
Hi i am aware of csv normalisation and agree with that but excel also dont respect it. That is i made this only as "feature resquest" but i also agree with you when you sayed that it is not your "business" if others dont follow standards   : -)

**Comment by almarklein** [comment]
Rereading this, I wonder if there's something we can do for tools like Excel and Numbers to import our tables. Let's reopen and adjust the title.

**Comment by almarklein** [comment]
Just checked. The CSV file that TimeTagger generates puts a space after each comma, to make it more readable. However, this space prevents the file from being read by Numbers. I strongly suspect that this is the case for Excel as well. I would not be surprised if that space violates the spec.

To summarize we should:
* don't add the space after commas
* escape double-quotes (#305)

**Comment by almarklein** [comment]
This issue is fixed in the latest version!
