### ISSUE TITLE
Report grouping by week and month

### ISSUE THREAD

**Issue by natpuch** [almarklein/timetagger#304]
Hey! 

I could not find an issue on this. There is a grouping by date (and date / tags) already. And I think, similarly, it would be nice to be able to group by week and month (and week | month / tags). 

It would be useful to track time spent working per week for example. 

Thanks!

**Comment by natpuch** [comment]
I just found this view which provides a nice view. I still think making it possible in the report view would be nice.

![Demo](https://user-images.githubusercontent.com/24622808/205386650-7bb69890-a950-4cb7-b587-a53897e71c9b.png)

**Comment by almarklein** [comment]
I think this makes sense. Thanks for the suggestion!

**Comment by almarklein** [comment]
Done!
