### ISSUE TITLE
Long lines overflow in PDF export 

### ISSUE THREAD

**Issue by mfru** [almarklein/timetagger#306]
**Expected behaviour**: Lines in exported PDF break into new lines when they are too long for the row.

**Actual behaviour**: Lines that are too long overflow the PDF document boundaries instead of breaking into a new line. 

**Version affected**: Whatever version is running on the hosted service :)

**Screenshot**
![timetagger-pdf-export-bug](https://user-images.githubusercontent.com/13270192/205961001-55515046-2107-4758-8862-42c69200af92.png)

**Comment by almarklein** [comment]
Thanks for the report! It would indeed be good if the line could break 👍 

To explain the technical background: the pdf is created using relatively low level construct, so to implement line breaking we'd have to measure text width and/or draw the description word by word.

**Comment by almarklein** [comment]
This is now working in the latest version!

**Comment by gitUser000** [comment]
Hi, 
it seems that long (long :-) ) description are not still well "perfectly" handed : 

- timetagger description input : 
GpppZp ZHQ pKur gGptZKn NKnvGrpZKn pKZnt/QZppZKn (NlGvGrNpv, NKQQp, DGlZQZtGrFZndGr, dptpprGp) #tgpt #pythkn

- pdf output : 
GpppZp ZHQ pKur gGptZKn NKnvGrpZKn pKZnt/QZppZKn (NlGvGrNpv, NKQQp, **_LINEBREAK_**
dptpprGp) #tgpt #pythkn

Missing : **_DGlZQZtGrFZndGr,_**

Thanks...

**Comment by almarklein** [comment]
Thanks for letting me know, this indeed looks like a bug. Tracking in #317
