### ISSUE TITLE
Doesn't recognize standard localhost ips as localhost

### ISSUE THREAD

**Issue by masukomi** [almarklein/timetagger#307]
building on issue #303 some docs say 0.0.0.0 some say 127.0.0.1 but you need to specifically use `localhost` in order to see the default login button. 

I'm thinking that maybe the software should recognize the standard set of 
- 127.0.0.1
- localhost
- 0.0.0.0 (maybe? might muck with docker)
- whatever the ipv6 equivalent of 127.0.0.1 is 

as all being localhost and providing the button.

**Comment by almarklein** [comment]
Good point.

Maybe not `0.0.0.0`, because if the server runs with that, it likely intends to accept outside connections, and it should have "proper" auth anyway.

**Comment by almarklein** [comment]
I checked, and both in the client (to decide whether or not to show the localhost-login-button) and on the server (to decide whether it can provide a token based on being localhost), the ip's 127.0.0.1 and "localhost" are both checked.

I tried ip6 but could not even connect, so the server does not support that a.t.m. Besides, ip6 is not necessary when running on localhost 🙃
