### ISSUE TITLE
Improve README in regards of multiple user auth

### ISSUE THREAD

**Issue by martin-braun** [almarklein/timetagger#312]
It is not clear to me how I would define multiple credentials using the enviroment variable or CLI argument method. 

Could you please clarify? Thanks.

**Comment by martin-braun** [comment]
I found my answer at https://timetagger.app/articles/selfhost2/

> You can add multiple users this way (separated by commas).

It should really be part of the main README.

**Comment by almarklein** [comment]
> It should really be part of the main README.

Good idea. I'm open to a  pull request to fix that 😉 ❤️
