### ISSUE TITLE
Negative time record

### ISSUE THREAD

**Issue by Kunniii** [almarklein/timetagger#314]
I let timtetagger record from 9pm to 2am, and the recorded time became negative.

![image](https://user-images.githubusercontent.com/57139436/210861424-08b6dd4a-8daa-461b-8aa7-25f01d6b68fa.png)

I cannot interact with that record to stop or delete it.

**Comment by Kunniii** [comment]
Current time at the time i took that screenshot is 2:07 AM, so i don't think the midnight time is the problem, because if 00:00 cause problem, then the recorded time should be -2h07m.

**Comment by almarklein** [comment]
I see a record that is running, that - for *some* reason - has its start time at 3:46 am. Is there anything special that you did to get the record in this state? E.g. was the machine's time or timezone changed?

**Comment by Kunniii** [comment]
I am not sure what happened there. I just let it run in the background and come back to check, so there is very little information. It may need to be investigated.

**Comment by Kunniii** [comment]
uhm, after a few hours, it still run in the background and the time become normal. I can delete it now.

Oh, and one more thing that may affect is the CLI. This record has been made by using the `timetagger start` command.

**Comment by almarklein** [comment]
> uhm, after a few hours, it still run in the background and the time become normal. I can delete it now.

Yeah, at some time, the start time will actually be in the past, and it will look normal again.

From my end, I think TimeTagger can be improved in two ways:
* Make it possible to delete such records while the're "flipped".
* Display the negative time properly. 

> Oh, and one more thing that may affect is the CLI. This record has been made by using the `timetagger start` command.

Ah, that helps determine the problem. When starting a record with the CLI tool, it will create a new record with the start time the current time (as a unit time stamp). This record is sent to the server (which stores the record without touching the time), and the record eventually ends up in the app.

One thing that would explain this behavior is that the machine where the CLI tool is running, and the one that runs the browser, have their clocks out of sync.

**Comment by almarklein** [comment]
I made a new issue for the points I mentioned:  #315

**Comment by Kunniii** [comment]
Thanks for info. Just a last few information.
+ My `timetagger` instance is running by Docker Compose.
+ I created a record on the CLI via `pip install`

I hope this situation will be resolve in the next update! Many thanks.

**Comment by almarklein** [comment]
Do the CLI and browser-tab-with-timetagger-app run on different machines?

For the record, #315 will make negative records look less awkward, but it does not help prevent them.

**Comment by Kunniii** [comment]
Everything is on localhost. 😀

**Comment by almarklein** [comment]
> Everything is on localhost. 😀

Mmm, then I'm very confused as to how this could happen 🤔  - Please let me know if you see it happen again!
