### ISSUE TITLE
Bug: Calender dropdown doesn't use "Week starts on" setting

### ISSUE THREAD

**Issue by Z3nto** [almarklein/timetagger#320]
The calender dropdowns at start/edit record popups doesn't use the "Week start on" setting.
At settings I've set "Monday" at "Week start on" setting, but the calendar dropdowns always show Sunday at first.

![image](https://user-images.githubusercontent.com/22791287/212879536-7c184e15-59d2-4e41-827e-3c15768c48d5.png)
![image](https://user-images.githubusercontent.com/22791287/212879706-84b77a0b-0395-49df-bce2-edb5452e0b94.png)

**Comment by almarklein** [comment]
It would indeed be more consistent if the calendar dropdown would follow the same rules. However, the dropdown is builtin by the browser (probably using you OS's settings?) and as far as I know we have no way to change this behavior.
