### ISSUE TITLE
Export to CSV, start and end date should be part of the filename

### ISSUE THREAD

**Issue by guettli** [almarklein/timetagger#321]
I export my times usualy for the last week on monday.

First I select "Report" then "last week".

Then I download the csv file.

It would be great, if the filename of the csvfile would be like this: "timetagger-YYYY-mm-DD--YYYY-mm-DD.csv"

With YYYY-mm-DD being the start/end date.

What do you think about this?

**Comment by almarklein** [comment]
I like that! 👍

**Comment by almarklein** [comment]
Done!

**Comment by guettli** [comment]
Yes, it works. Thank you.
