### ISSUE TITLE
Export: Datepickers would be nice

### ISSUE THREAD

**Issue by guettli** [almarklein/timetagger#334]
I think the pictures say it all. Datepickers would be nice, so that I can export individual date ranges.

![image](https://user-images.githubusercontent.com/414336/215989490-90f81ca9-72d8-4571-9cd6-cbf67c01c1d4.png)

Thank you for your overall support!

**Comment by almarklein** [comment]
The idea is to first select the appropriate range in the timeline and then go to the report. That said, I agree that it'd feel natural to have a date-picker there.

**Comment by guettli** [comment]
I know how to select a day, week or month. But I have no clue how to select an individual range.

**Comment by almarklein** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/3015475/216044379-01066863-7759-483c-8281-2008ee1a4959.png">

**Comment by guettli** [comment]
"Don't make me think" ....

If you don't want to provide a datepicker at this place (see initial  message), then a hyperlink to a place where I can change the from/to dates would be great.

**Comment by almarklein** [comment]
To be clear, I agree that there should be a date picker at the place that you suggested 😄

**Comment by almarklein** [comment]
Done!

**Comment by guettli** [comment]
thank you, looks good.
