### ISSUE TITLE
Search strings that contain uppercase characters will always fail to find any matches

### ISSUE THREAD

**Issue by michaellenaghan** [almarklein/timetagger#337]
If you have the text "Abc" in your records, a search for "Abc" will fail to find them.

Likewise, if you have the text "ABC" in your records, a search for "ABC" will fail to find them.

The problem is that the record text gets lowercased here:

https://github.com/almarklein/timetagger/blob/fdb229b73f0ad0cd5cf0854b94e6c3198cd12a23/timetagger/app/dialogs.py#L2513

but the words you search for retain their original case.

**Comment by almarklein** [comment]
Woops, that is a nasty oversight ... thanks for reporting this! I can indeed reproduce it.

**Comment by almarklein** [comment]
Took a while, but it's now fixed 🚀
