### ISSUE TITLE
Arrow/Page Up/Down jump two units?

### ISSUE THREAD

**Issue by guettli** [almarklein/timetagger#342]
I look at a day, after pressing "d".

Now I use arrow-Up (or page-Up) to get the previous day.

But the app jumps two days.

Example: Today is the second march. After pressing arrow-Up I see the 28th of february. After pressing arrow-up again I see the 26th february.

It is the same strange behaviour if I look at weeks. The app jumps two units, not one.

For me this is a bug, not a feature request.

**Comment by guettli** [comment]
That's strange. After reloading the browser window it works fine again. Sorry for the noise.

**Comment by almarklein** [comment]
Glad that it's resolved! Thanks for reporting nonetheless 👍
