### ISSUE TITLE
Extend Today Button behavior with Zoom to predefined time span.

### ISSUE THREAD

**Issue by MariusSp** [almarklein/timetagger#343]
Currently, you can setup a snap offset up to 5am. However, the timeline will show a complete day (24 hours) until the next day at 5am.

I suggest introducing something like a "workday offset" where I can define the default zoom level for a work day (i.e. 5am to 6pm).

This improves space utilization, since work is often done in a specific time period ("workday"), while the rest of the day has no entries at all. It also makes the view more readable if you have many short entries. 

Example image of the current view/behavior 
<img src="https://user-images.githubusercontent.com/35237005/226315815-5a44bce5-4b9b-4fd4-b9e0-3f5dce24d35b.png" height="500">

Example of improved view (by manually zooming in)
<img src="https://user-images.githubusercontent.com/35237005/226315897-99861bbf-b54f-44b5-977a-72c863c0d90e.png" height="500">

**Comment by ohare93** [comment]
Exactly this! I suggest the "Today" button can be reused for this feature. Tapping "Today" once would work as it normally does, and hitting it twice (or when Today is already selected) would zoom it down even further. This could be a 12 hour interval (which would be fine) or something configurable in the settings 👍 

This feature would be especially valuable on mobile, where the zoom buttons are not shown in portrait view 😭 It is tedious to switch to landscape, zoom in, then switch back to portrait.

**Comment by MariusSp** [comment]
This is not part of the latest release (23.6.1) yet, correct?

**Comment by almarklein** [comment]
> This is not part of the latest release (23.6.1) yet, correct?

No, I plan to do a release next week (which will include this change).

**Comment by almarklein** [comment]
This is now released and deployed 🚀

**Comment by MariusSp** [comment]
Thank you!
