### ISSUE TITLE
Remove 0h or make it less confusing by spacing or different font weight on date

### ISSUE THREAD

**Issue by martin-braun** [almarklein/timetagger#345]
<img width="158" alt="Screen Shot 2023-03-25 at 1 26 52 AM" src="https://user-images.githubusercontent.com/24259245/227667518-b43514d7-6f67-49e2-bce0-bf9e0c9f904c.png">

Kinda looks like "160h" and makes things hard to distinguish between dates when scrolling around.

Please add some spacing by left-aligning the date, consider removing "0h", also consider using a greater weight on the date font so it's easier to read.

Thanks. :)

**Comment by almarklein** [comment]
Done, and released!

**Comment by martin-braun** [comment]
@almarklein Thanks for that. This is definitely better. I still think the "0h" is a bit redundant, because the date implies that it's midnight anyways. If I was you, I would simply remove the "0h", but keep the date left aligned, but it's up to you. I still believe adding another space helps.

**Comment by almarklein** [comment]
Thanks for the feedback! I agree that it's somewhat redundant, but somehow it feels better (at least to me) to still have a time-unit there to indicate that the tick is indeed midnight.
