### ISSUE TITLE
Check date validity after leaving date field

### ISSUE THREAD

**Issue by digicommons** [almarklein/timetagger#346]
When adding a new record, the date picker prevents you from inputting certain days (probably 29-31, depending on the month).

As a useful default, the current date is preselected in the date picker. Once you try entering a day that doesn't exist in the current month, e.g. 31 in April or 29 in February, the date is reset to the current date. This forces the user to first enter the month and only then the day. With MM/DD/YYYY this might not be a problem, but when using DD.MM.YYY, this prevents speedy keyboard input.

Do you think this behavior could be adjusted?

![timetagger](https://user-images.githubusercontent.com/43313518/229729567-ff750d28-7424-4d5d-81e0-1510daf5a5c2.gif)

PS: Thank you for this great app, it has really grown on me!

**Comment by almarklein** [comment]
To answer your question more explicitly: no, it can't be fixed, unless we implement a date picker that does not use the builtin widget.

**Comment by digicommons** [comment]
Using the default browser date widget absolutely makes sense to me, though I am not able to reproduce the issue when using this browser widget elsewhere (https://jsfiddle.net/39pgrtx8/). Could it be that this is caused by some setter/validation logic and not the widget itself?

**Comment by almarklein** [comment]
Oh, I think you're right! Thanks for double-checking my claim! I've marked this as a bug.

**Comment by almarklein** [comment]
Fixed, and released!

**Comment by digicommons** [comment]
Thank you, works like a charm! 🎉
