### ISSUE TITLE
Report by description?

### ISSUE THREAD

**Issue by martin-braun** [almarklein/timetagger#348]
Say I work on a task multiple days. I use the "Resume" function to continue my task every day. After some days I'm done and I want to know how many hours this specific task took me. I tried to do a report, but I can only filter by tags, not by entire descriptions.

It would be nice, if there was a way to filter by full descriptions.

**Comment by almarklein** [comment]
My first impression is that you should simply use a new tag for this task :)  Tags are lightweight, so its just a matter of adding a `#tag` to the descriptions. You can make the tag secondary (via the tag-dialog) so it behaves better in sorting and grouping.

**Comment by almarklein** [comment]
*Some comments relative to this issue were made in #228.*

I still think that using a secondary tag would be the way to go. At least that's how I intended tags to work 😄  You mentioned in #348 that you feel that it pollutes things, by which I assume you mean the fact that the tag re-appears in the autocompletion. I'm interested in exploring this a bit further, because it means the tags don't feel as lightweight as I intended them to be. E.g. do you think it would it help if e.g. the autocompletion would forget about tags (at least the secondary tags) that are beyond a certain age? 

That said, I now also see the value of the report being able to group records that have the exact same description. And being able to group these in the report would not negatvely affect how tags work. So I'm moving this issue up in the priority queue.

**Comment by martin-braun** [comment]
Thanks for the explanation @martin-braun. I now also see that this is really a duplicate for #348. Will continue the discussion there, as that issue is still open.

_Originally posted by @almarklein in https://github.com/almarklein/timetagger/issues/228#issuecomment-1632023305_

Thanks for linking my own issue, I kinda forgot about it. 😂

> I still think that using a secondary tag would be the way to go. At least that's how I intended tags to work 😄 You mentioned in #348 that you feel that it pollutes things, by which I assume you mean the fact that the tag re-appears in the autocompletion. I'm interested in exploring this a bit further, because it means the tags don't feel as lightweight as I intended them to be. E.g. do you think it would it help if e.g. the autocompletion would forget about tags (at least the secondary tags) that are beyond a certain age?

Thank you for exploring this together with me. It's not just the autocompletion, it's also all my tasks I did in the past that I didn't follow your recommendation. Even worse: 

Right now, I use tags for partners, clients, customers, projects and kind. For instance, "#cteam #bestfoodsorg #foodapp #dev my task" (Sample: Developing "my task" in the CTeam for the Best Food Organization (client) on the Food App).

If I now add another tag for "my task", I can't combine all "#cteam #bestfoodsorg #foodapp #dev" together to see how much development I have made. I need to group tags by "#cteam #bestfoodsorg #foodapp #dev" to make a proper invoice without listing each and every task. Then for the detailed work sheet, I do actually need to group all tasks by description to give exact about how much each task took me.

I think using your approach will not let me do both. Also, even if there was a way using tags only, I can't remember all the tags when I start to tag for each task. It will also get too confusing for me.

> That said, I now also see the value of the report being able to group records that have the exact same description. And being able to group these in the report would not negatvely affect how tags work. So I'm moving this issue up in the priority queue.

Thank you for considering it. It means a lot to me as it would make my work so much easier. ❤️

**Comment by almarklein** [comment]
>  it's also all my tasks I did in the past that I didn't follow your recommendation.

I was going to suggest searching those tags and applying tags to them, but that would be tedious. #366 should help in such cases.

> Right now, I use tags for partners, clients, customers, projects and kind. For instance, "#cteam #bestfoodsorg #foodapp #dev my task" (Sample: Developing "my task" in the CTeam for the Best Food Organization (client) on the Food App).
>
> If I now add another tag for "my task", I can't combine all "#cteam #bestfoodsorg #foodapp #dev" together to see how much development I have made. I need to group tags by "#cteam #bestfoodsorg #foodapp #dev" to make a proper invoice without listing each and every task. Then for the detailed work sheet, I do actually need to group all tasks by description to give exact about how much each task took me.

Secondary tags could help here. By making `#my_task` a secondary task, you can include/exclude it in the grouping in the report. Though if some of your other tags are already secondary, I suppose you're out of luck 🤔.

> Thank you for considering it. 

Thanks for explaining your use-case. Relying on resume and using this intended new feature would be an interesting complimentary workflow!

**Comment by martin-braun** [comment]
Bulk editing and secondary tasks could help, but I fear to lose overview of my tags having so many available. I think it can't hurt to offer this group by description functionality anyways. It should be easier to implement and ultimately everybody wants to use software the way it works best for them. I'm not so good at tag guessing, so I'm happy having only a few tags and not tags for each and every different task, I must say.

**Comment by almarklein** [comment]
> I think it can't hurt to offer this group by description functionality anyways.

Just to be clear, I agree (now) 😄

**Comment by almarklein** [comment]
Implemented! New release is available (and online).
