### ISSUE TITLE
Rethinking navigation between days

### ISSUE THREAD

**Issue by guettli** [almarklein/timetagger#350]
If I want to go to the previous day, I first hit the left-arrow key.

Somehow this is inuitive for me.

It is called "timeline" and in most cases the past is on the left side and the future is on the right side.

If I were you, I would change the keybinding.

I just wanted to tell you this.

**Comment by almarklein** [comment]
I understand the habit to think of the past as being on the left side. However, in TimeTagger the timeline is positioned vertically with the time moving downwards. In this setting, the most intuitive binding to move back in time is "up".

It would be possible to assign "left" to move backwards too, but it is already bound to zooming out, so changing it would break the workflow of other users. I guess it's a matter of retraining the fingers to hit "up" instead :)

**Comment by guettli** [comment]
I use the google calendar. The hours in one day are from top to bottom. The days are from left to right. That's what I am used to.

**Comment by almarklein** [comment]
I understand that switching between apps can be confusing. But this is not Google Calendar, so the most sensible default keybindings are different.

I think the best solution would be for the keys to be configurable. They are not at the moment, but I can create an issue for it. What do you think?

**Comment by guettli** [comment]
Yes, makes sense. to make keybindings configurable.

**Comment by almarklein** [comment]
Ok, closing this in favor of #351.
