### ISSUE TITLE
Breakdown of the "General" group

### ISSUE THREAD

**Issue by oneironautd** [almarklein/timetagger#358]
Right now, the items clocked under a tag or combination of tags are grouped as "General", it would be nice if we could get a breakdown of them based on their description. 

![image](https://user-images.githubusercontent.com/55920099/236293720-26e15d8c-3ff2-4af7-9d37-e180579bca6e.png)

For example, if I had logged these entries,

```
1984 #book 1h
Brave new world #book 2h
1984 #book 30m
```

And I navigate to #book, instead of showing "General 3h30m", it could be shown as

```
1984 1h30m
Brave new world 2h
```
Some exceptional cases, such as records with no text/description, can be grouped under General or Untitled.

**Comment by lanceomni** [comment]
If you add a secondary tag like #1984 and #Bravenewworld they will be broken out of General and displayed separately. 

You can then click report and see the descriptions.  There is a screenshot showing my #unbilled primary tag with the secondary tags showing (two names blocked out)

![IMG_6771](https://user-images.githubusercontent.com/194573/236300350-9e8293fd-a08f-4308-80a7-a87811528a6a.jpeg)

**Comment by almarklein** [comment]
This is exactly what tags are for 😄 

You may experience a hesitance to create occasional tags like that (I feel that too sometimes, to be honest), but tags are designed to be lightweight and should not be "in the way" anywhere. I'd suggest to try and just create some more tags, mark them as secondary, and see how that works out.

I'm closing this, because I don't intend to implement grouping based on the description themselves (they were never meant for that). However, if you have ideas to make a workflow using tags more smooth, I'd love to hear them! (One thing that comes to mind right now: an easier way to create secondary tags, without having to enter the tag dialog.)

**Comment by oneironautd** [comment]
> You may experience a hesitance to create occasional tags like that (I feel that too sometimes, to be honest), but tags are designed to be lightweight and should not be "in the way" anywhere. I'd suggest to try and just create some more tags, mark them as secondary, and see how that works out.

I'm currently using secondary tags for this purpose, as you mentioned, but I was just afraid of creating too many tags and cluttering up the overview, so I suggested this idea.

> I'm closing this, because I don't intend to implement grouping based on the description themselves (they were never meant for that).

It's totally fine. Usually other time tracking systems I have used report the clocked time by title and the tags are used to filter or group them. I was expecting the same behavior here as I was using the description like a title.

> One thing that comes to mind right now: an easier way to create secondary tags, without having to enter the tag dialog.

Maybe we can define a new symbol for the secondary tag like "@" or we can specify the priority at the end of the tag when typing the description like "#book!2" (this means we can also do "#book!1" but it is not required as it is implied by writing "#book"). Sorry if these ideas are terrible.

Also, I really love using this application, thanks for your work.

**Comment by almarklein** [comment]
> [...] but I was just afraid of creating too many tags and cluttering up the overview

Could you please expand on that? As I understood it you do want to have subgroups, so how does this introduce clutter?

Thinking out loud ... perhaps you mean that you'd only like the subgroups to appear when you select a (primary) tag? In which case we could perhaps introduce an option to hide secondary tags from the main overview ...

**Comment by oneironautd** [comment]
> In which case we could perhaps introduce an option to hide secondary tags from the main overview

Yes that would be nice.
