### ISSUE TITLE
Better documentation for the self-hosted version

### ISSUE THREAD

**Issue by brnl** [almarklein/timetagger#36]
The README.md is lacking critical information on how to get the project running.

**Installation**
pip(3) install X is nice but then what?

**Uninstall**
How to cleanly uninstall?

**Requirements**
What python version is required?

For now it was unusable for me.

**Comment by almarklein** [comment]
Thanks for the issue! Yes, the docs need work ...

**Comment by almarklein** [comment]
I made some improvements to help people on their way.  I made a new issue for API docs: #42. If there are any other things unclear, just let me know!
