### ISSUE TITLE
Add an option to display time in days

### ISSUE THREAD

**Issue by oneironautd** [almarklein/timetagger#360]
It's easier to read the total time in days 5d2h30m instead of something like 122h30m, so it would be nice to add this option here.

![image](https://user-images.githubusercontent.com/55920099/236621598-068e29f0-98ed-43e9-82ae-531873a3f5e0.png)

**Comment by almarklein** [comment]
To me it feels somewhat weird to express total-spent-time in days, because one rarely does the same thing for consecutive days, so the number makes little sense to me.

But this can be just me 😄, I'd be happy to add an option for that 👍

**Comment by oneironautd** [comment]
> To me it feels somewhat weird to express total-spent-time in days, because one rarely does the same thing for consecutive days, so the number makes little sense to me.

It's not about the time spent on a single task, but the total time shown in the overview. For example, if I track 12 hours a day and then go to the weekly view, it will show me something like 84 hours, which is much less meaningful than 3 days 12 hours.

Also, I have used Emacs org-mode and Logseq for time tracking in the past, they display total time in days, so it is a bit familiar to me.

**Comment by almarklein** [comment]
This feature is now available in the latest release.
