### ISSUE TITLE
Scroll timeline to selected search result 

### ISSUE THREAD

**Issue by mpflanzer** [almarklein/timetagger#361]
Hi,

It would be really nice if the search results list would allow to jump to a result I select, i.e. scroll the timeline to the point in time of the search result. Aligned with that it could also be nice to have the option to get a permanent link for events in the timeline. So that I could share them with someone else and they would directly start with the timeline at the given event/time.

Would that be an easy addition or would it require quite some changes in the code base?

Cheers,
Moritz

**Comment by almarklein** [comment]
> scroll the timeline to the point in time of the search result

That's certainly feasible, and I think it would be a very useful addition!

> the option to get a permanent link for events in the timeline. So that I could share them with someone else and they would directly start with the timeline at the given event/time.

In your idea, if someone used that link, it would simply open their own timeline (not showing *your*) records, right? It'd be a way to share timeline ranges. I think this can be made to work, e.g. using hash localtios, e.g. `https://timetagger.app/app/#timeline=123-456`.

**Comment by mpflanzer** [comment]
Yes, I had in mind that it would just open the timeline for the account that is currently logged in at the given point. For example like the anchor in the URL that you propose

**Comment by almarklein** [comment]
This option is now available.
