### ISSUE TITLE
Add sidetrack / interruptions option

### ISSUE THREAD

**Issue by joshbmarshall** [almarklein/timetagger#363]
It looks like if I'm working on a block of time and get a call from a different customer or project, I have to stop what I'm doing, log the new task, and then if I go back to what I was doing, start another block.

Would be useful to have the option for an interruption on a project. A phone call or a break for lunch is a perfect example.

**Comment by almarklein** [comment]
This is exactly what the "resume" button is for 👍 . You start the new task (old one gets stopped automatically). When the interruption ends, you click on the record corresponding to the original task, and hit "resume" to start a record with the same description.
