### ISSUE TITLE
Scrolling the timeframe makes it infinitely scroll down.

### ISSUE THREAD

**Issue by jtagcat** [almarklein/timetagger#364]
1. Dragging with left click
2. Clicking Today
3. Briefly scrolling down
4. Scrolling up
5. Using up/down buttons (only thing that works)

https://github.com/almarklein/timetagger/assets/38327267/753dff26-b2e9-48ee-a478-80e9172cfe1f

**Comment by almarklein** [comment]
Hi!

Are these the steps to reproduce the observed behavior? At what point does it start going down indefinitel

Odd behavior like this might be very device specific. Could you please provide more details on: the browser type, mobile or pc, windows/mac/linux, using the mouse or the touchpad?

**Comment by jtagcat** [comment]
These are all variants to reproduce the problem. After each variant, I refresh the page.

Firefox on Linux. I can't reproduce it today at all(?)

**Comment by almarklein** [comment]
> I can't reproduce it today at all(?)

Oh, annoying that its not reproducible, but if it stays a way I guess it's a good thing. Perhaps it was a browser glitch of some sort?  Anyway, please let it know here if it returns!
