### ISSUE TITLE
Round Up to Whole Minute

### ISSUE THREAD

**Issue by atomdmac** [almarklein/timetagger#371]
I've been working on some integration with my code editor that allows me to track the length of time that a have any given file open.  The issue I'm having is that I switch between files pretty often, sometimes spending less than a minute per file.  However, `timetagger` seems to round _down_ to the whole minute instead of _up_ which means I end up with a lot of intervals that have a duration of `0m`.

Could we have an option to round _up_ instead of down?

**Comment by almarklein** [comment]
Hi!

> However, timetagger seems to round down to the whole minute instead of up which means I end up with a lot of intervals that have a duration of 0m.

Actually, the app rounds towards the nearest minute, so a duration of 32s would become 1m. Rounding the time up does not feel like a correct solution ...

What about, when the duration is smaller than a minute, it is shown in seconds instead? I'm implementing this in https://github.com/almarklein/timetagger/pull/376, along with a few related fixes to the display of durations.

**Comment by almarklein** [comment]
Closing as fixed by #376. Feel free to re-open if your case is not properly covered yet by this change.
