### ISSUE TITLE
new issues with pullrequest 389

### ISSUE THREAD

**Issue by az18** [almarklein/timetagger#392]
https://github.com/almarklein/timetagger/pull/389 has created some issues:

- hours in decimals not working anymore 
  - ![image](https://github.com/almarklein/timetagger/assets/11908231/53314a7d-01d1-457e-8947-ed6e461d736a)

- sometimes i don't have all entries in the reporting. but i don't know how to reproduce that

**Comment by almarklein** [comment]
Thanks for the heads-up! I can indeed reproduce it. It was an easy fix, since it was caused by a silly typo 😕 

I am looking at your other comment, and I indeed see some weird things ...

**Comment by almarklein** [comment]
Fixed both!

**Comment by az18** [comment]
awesome! thank's a lot :)
i really appreciate your work here :100:  awesome tool
