### ISSUE TITLE
Non-root tag is set to "latest"

### ISSUE THREAD

**Issue by modem7** [almarklein/timetagger#396]
[v23.9.1-nonroot](https://github.com/users/almarklein/packages/container/timetagger/125164910?tag=v23.9.1-nonroot) is set to latest, which is breaking normal root containers. 

setting tag manually to [v23.9.1](https://github.com/users/almarklein/packages/container/timetagger/125164813?tag=v23.9.1) resolves.

https://github.com/almarklein/timetagger/pull/357 is a breaking change.

**Comment by almarklein** [comment]
Thanks for the heads-up, I made a fix and will make a new release in a bit.

**Comment by almarklein** [comment]
Nope, that did not work 😕 

@modem7 or @danielhass any idea how to make the original image the defatault/latest?

**Comment by almarklein** [comment]
Nevermind!  I think I checked the packages pages a little too soon, right at the moment when the `root`  image was build but the `nonroot`  was not. So it worked exactly as I hoped 🎉 . Sorry for the noise!
