### ISSUE TITLE
Can not create report when tag selected in Overview

### ISSUE THREAD

**Issue by flow7** [almarklein/timetagger#401]
Hi there,
it seems a #bug to me, or I misunderstand things ;) 
V. 23.9.1

When in Overview I click the Report Icon or R and the report dialog pops up -- All good!
When in Overview I select a tag (any tag, any number of tags) and click the Report button or the R, nothing happens.

I seem to remember it worked once, but then stopped. Can that be?
I've tried a whole range of different browsers, same thing everywhere.

Thanks!

**Comment by flow7** [comment]
damn, yes, now it works :) -- not sure what it was, can't reproduce myself at this point.
sorry for the false alarm ;)

**Comment by almarklein** [comment]
No worries! 👍
