### ISSUE TITLE
[idea] Bigger start / stop button for mobile design

### ISSUE THREAD

**Issue by Tagirijus** [almarklein/timetagger#402]
_Some pre-info ahead:_

_I found your project while looking out for other possible time tracking solutions. And this project really stuck to my mind. I really like the flexible idea of having tags instead of e.g. "client > project > task > subtask" hierarchy! I thought to just post some ideas here on Github in case you might find it useful! I'll start with this little idea and post the others in different issues here. Hope that's okay!_

**The actual idea:**
On the mobile design it would be helpful to have bigger start and stop buttons for starting or stopping a task recording.

**Comment by almarklein** [comment]
> Hope that's okay!

Thanks for all the suggestions! It's indeed more convenient to have them in separate issues like you did 👍 

> On the mobile design it would be helpful to have bigger start and stop buttons for starting or stopping a task recording.

On mobile, screen space is scarce, but making that button easier to reach seems reasonable. Will certainly consider it!

**Comment by almarklein** [comment]
Done. I made all buttons a bit bigger, because making the one button bigger did not look well.

**Comment by Tagirijus** [comment]
Also it is a bit more centered. Nice, thanks! (=
