### ISSUE TITLE
[idea] Y for year time range

### ISSUE THREAD

**Issue by Tagirijus** [almarklein/timetagger#406]
We have _D_ as a shortcut for setting the time range to day and _M_ for setting it to month. _Y_ seems free for now. Why not using it for setting the time range to year?

**Comment by Tagirijus** [comment]
I just noticed that this issue is related to #351 :v:

**Comment by almarklein** [comment]
If I recall correctly I did not bind it because it's much less common to move to a year view. But since the letter is free, it makes sense to be consistent and have a binding for each time range ...

**Comment by almarklein** [comment]
Closed by #412
