### ISSUE TITLE
Use rounded numbers for totals and subtotals

### ISSUE THREAD

**Issue by michaellenaghan** [almarklein/timetagger#408]
My wife noticed that CSV and PDF reports can end up with slightly different totals and subtotals. (By "CSV" I mean "CSV imported into Excel.")

I assume that reports are rounding the entries for days, but totalling and subtotalling using the unrounded numbers.

Here are two possible solutions.

First, total and subtotal using rounded numbers.

Second, export to CSV using unrounded numbers.

From an accounting perspective, the first probably makes more sense. If you bill for 1.5 hours and 1.5 hours you expect the total billed to be 3.0, not 2.9.

**Comment by almarklein** [comment]
> My wife noticed that CSV and PDF reports can end up with slightly different totals and subtotals. 

Oh, that's interesting. I will certainly look into that. Is the difference observed in the actual numbers in the sheet, or only after summing the numbers in Excel?

> First, total and subtotal using rounded numbers.
> Second, export to CSV using unrounded numbers.

I suppose there's something to say for both approaches. This is also related to how many decimals are used to express the numbers. Thinking out loud: perhaps rounding by the minute and choosing a significance high enough to cover that.

**Comment by almarklein** [comment]
Marking this as a bug, making it a bit higher priority.

**Comment by michaellenaghan** [comment]
> only after summing the numbers in Excel

Yes, only after summing the numbers in Excel.

> I suppose there's something to say for both approaches. 

The benefit to "total and subtotal using rounded numbers" is that anyone with a calculator would get the same result. 

If "greater accuracy" was a goal, I think the right choice would be to just make the number of decimal points configurable. I'm not sure that more accuracy matters to most people though? Unless, of course, your hourly rate is very, very high. :-)

**Comment by almarklein** [comment]
Fixed! Totals are calculated by summing the rounded numbers. And the precision (number of decimals) can be configured, so we now kinda have both ways 🚀

**Comment by michaellenaghan** [comment]
Saw that, very nice, thank you!
