### ISSUE TITLE
How to add second user

### ISSUE THREAD

**Issue by Schmandre** [almarklein/timetagger#416]
Hi there,

I need some help with adding a new user for time tracking. My girlfriend and I work for different ambulance services and we would like to record our times separately using our own user accounts. 

I tried adding another line in the docker-compose but it seems that only the last line is recognized as a valid user. 

Can you guide me on how to add a second user to the docker container? 

```
version: "3"
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "3030:80"
    volumes:
      - ./data:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=user1:$$censored
      - TIMETAGGER_CREDENTIALS=user2:$$censored```

Thank you in advance for your assistance.

**Comment by almarklein** [comment]
Hey,

You can separate credentials using a comma or semicolon:

https://github.com/almarklein/timetagger/blob/45ba1736af6b53cd7c3ef339fc59a3618b7ff72e/timetagger/__main__.py#L228-L233
