### ISSUE TITLE
v23.11.1 doesn't work in Safari; `/timetagger/app/` is completely blank

### ISSUE THREAD

**Issue by michaellenaghan** [almarklein/timetagger#423]
It *does* work in Chrome and Firefox.

Here's a screenshot of Safari's console log:

<img width="1440" alt="Screenshot 2023-11-08 at 1 36 50 PM" src="https://github.com/almarklein/timetagger/assets/176481/047e5dbf-14ae-48a5-a28f-8bc7e33464e5">

There are, of course, no errors in Chrome's console log.

P.S. I've tried both force-reloading and using a private window; it isn't a state-related problem.

**Comment by almarklein** [comment]
I can indeed reproduce this bug. Looking into it ...

**Comment by almarklein** [comment]
Found the culprit: it's related to the resize obserer introduced in #418. Now looking into the best way to resolve.

**Comment by almarklein** [comment]
Fixed! Thanks for the report! 

xref #75

**Comment by michaellenaghan** [comment]
Yowza, thank you!
