### ISSUE TITLE
Total time was right (i.e., respected the filter), now it's wrong (i.e., doesn't respect the filter)?

### ISSUE THREAD

**Issue by michaellenaghan** [almarklein/timetagger#432]
Go to a day with multiple tags. Now filter by one of the tags, and click Report. 

The Total, I believe, used to be the total of the _filtered_ time. Now it's the Total of the entire day/week/month/etc.

That's a problem if, for example, the tag you're filtering on represents a client, and you want to Save PDF to send the client an invoice. 

Rather than Total being the total time for that client, it's the total of all work performed for all clients in the period.

**Comment by almarklein** [comment]
I can indeed reproduce this. Ai that's a bug for sure. Introduced in #430, most likely. I'm on it.

**Comment by almarklein** [comment]
Fixed, and made a new release.

**Comment by michaellenaghan** [comment]
Thank you!

**Comment by almarklein** [comment]
Sorry for the inconvenience!
