### ISSUE TITLE
Too small scale of the canvas on a high-res monitor

### ISSUE THREAD

**Issue by anantakrishna** [almarklein/timetagger#436]
In the screenshot we can see how small are all the details in the canvas in comparison to normal HTML elements.

![2023-12-11_00-50](https://github.com/almarklein/timetagger/assets/6065071/58aa8f2d-3136-4a3e-929b-284dcbf51668)

Besides that, the elements inside the canvas do not react on clicking.

---
Probably it is related to my monitor resolution and scale in Windows:

![image](https://github.com/almarklein/timetagger/assets/6065071/3ac20b21-d4d9-4985-9941-b569061124ea)

Firefox 120.0.1

**Comment by almarklein** [comment]
Hi @anantakrishna, that's not the intended behavior, thanks for reporting this!

Could you please try and open the developer console (F12) and check what the value of `devicePixelRatio` is (in the console)?

When I have access to a Windows laptop (probably later today) I can try and reproduce this with the Windows scale settings.

**Comment by anantakrishna** [comment]
> Could you please try and open the developer console (F12) and check what the value of `devicePixelRatio` is (in the console)?

It's 
```
devicePixelRatio
1
```

I'm ready for any further assistance in diagnosing.

**Comment by anantakrishna** [comment]
Interestingly, in Chromium it's `2`, and the app renders properly:

![image](https://github.com/almarklein/timetagger/assets/6065071/f98d7891-cec9-4f0f-9125-6d52ba2c2ee4)

**Comment by almarklein** [comment]
Thanks for checking. It looks like the value for `devicePixelRatio` is off then, and from the p.o.v. of the timetagger source we cannot do much about it. 

Could you change the browser zoom to its default? (menu > zoom).  I half-suspect that the zoom was set at some point, and Firefox remembers it for the page. On the other hand, the menu (which is html) does not seem to suffer 🤔 

I know this is a bit of an open door, but have you tried restarting your browser? 

As a workaround, you could zoom-in the page, although the menus will get zoomed in as well...

**Comment by anantakrishna** [comment]
I've found out the reason!

This Firefox's bug describes it best: https://bugzilla.mozilla.org/show_bug.cgi?id=1554751

In short, I have `resistFingerprinting` setting turned on in Firefox, which entails spoofing `devicePixelRatio` as `1`. You wanted it, you get it…

Therefore, not a bug of TimeTagger.

**Comment by anantakrishna** [comment]
In fairness, this applies only to those users who have enabled this `resistFingerprinting` setting themselves.
