### ISSUE TITLE
wrong timezone at first booking

### ISSUE THREAD

**Issue by lachnerd** [almarklein/timetagger#437]
Hi,
i realized that timetagger always start the first booking of a day in the wrong timezone.

For example i have "UTC+1:00"
<img width="225" alt="image" src="https://github.com/almarklein/timetagger/assets/25339466/3fa0034a-de09-495b-82e8-09040707495b">
 but first booking is only UTC.
So it 08:25 here but timetagger says 07:25 :-(

Is this a bug or do i have some misconfig maybe going on here ?

**Comment by almarklein** [comment]
Hi,

TimeTagger uses the time-information from the browser, so everything should work automatically. In the image below, the dashed line represents the current time (it's 9:09 here now, I'm in the same time-zone as you), is that in the correct place for you?

<img width="269" alt="image" src="https://github.com/almarklein/timetagger/assets/3015475/2affbe53-61c2-41b4-9972-855fcaf23ae6">

One thing that comes to mind is that you select "already done" when creating the record. This sets the start time to the end-time of the previous record, or to an hour ago if the previous record was some time ago. Perhaps this hour offset explains the start time of your record?

**Comment by lachnerd** [comment]
thx, current timeline is correct but i'll check if it may be cause auf this already done thing

**Comment by lachnerd** [comment]
first time tag of the day:
<img width="799" alt="image" src="https://github.com/almarklein/timetagger/assets/25339466/288a2e44-1189-4bef-a48c-9f7b48bf0a9b">

**Comment by lachnerd** [comment]
ok, so here it's the 1h default, i understand. However i wouldn't have expected this behaviour.
My peronsal usecase is very likely like this one - started working at 08:30 - after booting miy device etc. i realize that i have time to tag but thats usually not an hour in the past.  
How about starting at the current time doing one "-" (right now it's max. 5 minutes) ?

**Comment by almarklein** [comment]
The default start time is indeed very arbitrary. It depends a lot on the use-case, and the habits of the user, what a most sensible value is. Therefore, every time I change the default, I make a few users happy but another few users sad. 

My recommendation for you would be to start the record using "start now". Then open the record again and hit the minus button after the start time a few times. Or select the record in the timeline and drag it back a bit.
