### ISSUE TITLE
Removal of PWA support on iOS in EU

### ISSUE THREAD

**Issue by danielhass** [almarklein/timetagger#448]
Hi @almarklein, Timetagger should be affected by the upcoming removal of PWA support on iOS in the EU right?

Source: https://developer.apple.com/support/dma-and-apps-in-the-eu/#dev-qa

If this is correct I think it would be worth to fill out the Open Web Advocacy survey:

https://open-web-advocacy.org/apple-attempts-killing-webapps/

**Comment by almarklein** [comment]
Thanks for the heads-up @danielhass! I was not yet aware of this. This would be very sad, the PWA model was a great way to deliver the app without the hassle of going to the app store 😢  I filled in the OWA form.

**Comment by danielhass** [comment]
@almarklein welcome! Thanks for taking the time to fill out the survey, I hope this will get sorted out..

**Comment by almarklein** [comment]
> I hope this will get sorted out.

I hope so too, but I don't expect Apple to change its mind that easily ...

**Comment by danielhass** [comment]
You're probably right..

**Comment by danielhass** [comment]
@almarklein - I think we are safe for now 😉 

https://open-web-advocacy.org/blog/apple-backs-off-killing-web-apps/

Thanks for raising your voice!

**Comment by almarklein** [comment]
Danger averted! (for now)  Thanks @danielhass!
