### ISSUE TITLE
Notification on starting an activity

### ISSUE THREAD

**Issue by lokesh-krishna** [almarklein/timetagger#453]
Notification daemons such as [dunst](https://dunst-project.org/documentation/#SCRIPTING) offer scripting whenever a notification is triggered. It would be really handy if Timetagger put out a standard notification whenever an activity started. This could be used by users to trigger scripts that could maybe set DND (the use case that I personally have in mind) or even other things.

Could you please consider adding such a feature?

----

Related:  #460

**Comment by almarklein** [comment]
You mean sending [web notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)? Will dunst pick these up, or is there anything special we'd need to do?

**Comment by lokesh-krishna** [comment]
Web notifications! The kind shown for when it's time for a break. I'm presently manually enabling DND and using the break notification to disable it.

Thank you so much for considering this!

**Comment by almarklein** [comment]
Ok, I think this can work. I would probably create a setting to enable notifications (opt-in). Other than that, it should not be too hard to add.
