### ISSUE TITLE
KeyError when deleting an entry

### ISSUE THREAD

**Issue by mahadi** [almarklein/timetagger#48]
Hi, i am running the local setup and when i am delting an entry i get a message box "KeyError: some token" everytime. But the entry gets deleted finally.
Not sure where this comes from.
Do you have an idea?

Thank you for this nice project!

**Comment by almarklein** [comment]
Hi @mahadi, thanks for reporting this!

I can indeed reproduce this. In the demo this does not happen (which is probably why I had not seen this yet), but in the app it is. Looking into it!
