### ISSUE TITLE
Could not get token: ValueError in request handler: Invalid salt

### ISSUE THREAD

**Issue by j0nsgh** [almarklein/timetagger#485]
I've created a docker, used the cred page to generate a docker credential, added it into my YAML, but I'm constantly met with:

Could not get token: ValueError in request handler: Invalid salt

**Comment by almarklein** [comment]
I suspect the credentials are not properly escaped. Have you also tried the version with double dollar signs, for instance?

**Comment by JanLouisP** [comment]
I had the same issue. For me it fixed it using the Raw Credentials. I am using CasaOs, when I insert it there it escapes automaticaly, so I had double escaped.

**Comment by almarklein** [comment]
I'm going to assume the original issue is similar, and close this issue. @j0nsgh feel free to respond/reopen if the issue persists.

**Comment by j0nsgh** [comment]
Hey there, so funny thing, Tuesday I finally had time to rework the container build and as @JanLouisP eluded to, I too am using CASAOS so once I discovered the escapes, I adjusted and it resolved the issue.  Hadn't had a chance to respond back, but yup all good and can close!
