### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by InteractionEngineer** [almarklein/timetagger#493]
While manually adding entries from the past I pressed enter to confirm my "recording". I used the numpad enter key if that matters. One tag included an "ü" (german "ue") - which was not a problem before, when I confirmed my recordings with a click of the corresponding button. Immediately after pressing enter I saw in the background of the recording dialog that all previous entries were removed. Accessing the app with my credentials now leads to theses error messages:

![Bildschirmfoto 2024-07-15 um 23 20 19](https://github.com/user-attachments/assets/de046e31-14cf-4446-98e2-aa4ec83f3d75)
![Bildschirmfoto 2024-07-15 um 23 19 47](https://github.com/user-attachments/assets/974b0105-1a86-4885-bc2d-27325b825a2d)
![Bildschirmfoto 2024-07-15 um 23 19 29](https://github.com/user-attachments/assets/1a6ccd8f-c761-464e-8c6f-e50edde3d7ba)

**Comment by almarklein** [comment]
Thanks for reporting this! I've not seen this before. Looking into it.

**Comment by almarklein** [comment]
Firstly, I don't think your records are actually gone.

### Some context

In addition to storing the records themselves, the app maintains an in-memory data-structure (similar to a binary heap) that allows it to quickly query the summaries that are shown on the right. The `_update_bins()` method updates this data structure. This happens recursively. Somehow this recursion resulted in an infinite loop. I don't see how this could have happened.

### Resolving

Could you try to refresh the page? The app should re-build this data structure from the records. It could be that the error persists, but then I have some more info on the cause.

For good measure, also try logging out and in again. That should clear the app's local cache.

**Comment by InteractionEngineer** [comment]
Hi there! Thanks for your quick reply. I was also positive about not have lost any data - great to hear this confirmed. Immediately after the error occurred I tried some of the common ways to solve it. I already:
- refreshed the page 
- logged out and back in
- tried with another browser

None of these measures helped unfortunately.

**Comment by almarklein** [comment]
Thanks for the feedback! Ok, in that case there is probably something about the record times that causes the recursion. 

It would help a lot if I could reproduce the error, so I can explore what's going on. I can than also attempt to fix it, and confirm whether the fix works or not.

If you're up for it, could you please try:
* menu -> export all records, use unix timestamps.
* Copy the table to a spreadsheet, and then remove the tags and description columns.
* Send me the data (only start-stop times) via email (support@timetagger.app)

If you don't feel comfortable sending the full data, you could try the following:
* Open https://timetagger.app/app/sandbox
* Via menu -> import records, you import the exported data, see if the error is there.
* Refresh the page, and repeat with a subset of the data.
* Send me the minimal subset that reproduces the error.

**Comment by InteractionEngineer** [comment]
What I forgot to mention: **I run this as a Docker container** on my home server. I you advise me, I can log into that container and export the wanted file directly.

**Comment by almarklein** [comment]
Can you run a Python script on your work machine? I could create a small script to extract the data via the web api.

**Comment by InteractionEngineer** [comment]
Of course, no problem!

**Comment by almarklein** [comment]
```py

import datetime
import requests

# Replace with the url of your instance
base_url = "https://timetagger.app/api/v2/"

# Fill in the api token (from the account page)
api_token = ""

# Get an appropriate range
date1 = datetime.date(2024, 1, 1)
date2 = datetime.date(2024, 12, 31)

timestamp1 = int(time.mktime(date1.timetuple()))
timestamp2 = int(time.mktime(date2.timetuple()))
r = requests.get(base_url + f"records?timerange={timestamp1}-{timestamp2}", headers={"authtoken": api_token})

r.raise_for_status()
records = r.json()["records"]


for record in records:
    print(f"{record['t1']},{record['t2']}")
```

**Comment by InteractionEngineer** [comment]
Awesome!
I quickly ran your script and got the following output:

`start, stop
1612982100,1612985640
1620557100,1620557760
1622755080,1622761320
1622797200,1622799180
1624996620,1624998060
1625062920,1625063820`

I choose 2020 to 2022 as range because the error occurred entering data from 2021.

**Comment by almarklein** [comment]
Is that all the data (that's just 6 records)?

**Comment by InteractionEngineer** [comment]
Indeed, I was just starting to import old data. New data would be from this year. I would prefer not to publish those. Are they important as well? The error surely results out of those 6 entries.

**Comment by almarklein** [comment]
Here's a script to see if there's records with odd dates.

```py
import time
import datetime
import requests

# Replace with the url of your instance
base_url = "https://timetagger.app/api/v2/"

# Fill in the api token (from the account page)
api_token = ""

# Get an appropriate range
date1 = datetime.date(1, 1, 1)
date2 = datetime.date(9000, 12, 31)

timestamp1 = 0
timestamp2 = 2218768380000
response = requests.get(base_url + f"records?timerange={timestamp1}-{timestamp2}", headers={"authtoken": api_token})
response.raise_for_status()

records = response.json()["records"]
records = sorted(records, key=lambda r: r["t1"])

def show_record(prefix, r):
    dt1 = datetime.datetime.fromtimestamp(r['t1'])
    dt2 = datetime.datetime.fromtimestamp(r['t2'])
    print(f"{prefix}: {r['key']}, from {dt1} to {dt2}")
    
print(f"{len(records)} records")
show_record("earliest", records[0])
show_record("latest", records[-1])

early_records = [r for r in records if datetime.datetime.fromtimestamp(r['t1']) < datetime.datetime(2000, 1, 1)]
for r in early_records:
    show_record("early", r)
future_records = [r for r in records if datetime.datetime.fromtimestamp(r['t2']) > datetime.datetime(2025, 1, 1)]
for r in future_records:
    show_record("future", r)
```

If there are records in a distant past or far future, these are likely the result of accidentally entering a wrong date in the the record dialog. An these may be causing the issue.

They can be fixed with something like this (I can help out write a more specific script):
```py
def update_record(r):
    response = requests.put(base_url + "records", headers={"authtoken": api_token}, json=[r])
    response.raise_for_status()
    print(f"updated {r['key']}")

# .. update any records

# .. then send each record to server using  update_record()
```

**Comment by almarklein** [comment]
Oh interesting ...

Try replacing the request with this
```py
response = requests.get(base_url + f"updates?since=0", headers={"authtoken": api_token})
response.raise_for_status()

records = response.json()["records"]
records = sorted(records, key=lambda r: r["t1"])
```

**Comment by InteractionEngineer** [comment]
There we go!

`22 records
earliest: xNOMAreB, from 1921-02-27 00:19:00 to 1921-02-27 00:43:00
latest: DBRxTXKV, from 2024-07-15 22:14:28 to 2024-07-15 22:35:00
early: xNOMAreB, from 1921-02-27 00:19:00 to 1921-02-27 00:43:00`

**Comment by almarklein** [comment]
This should do the trick :)
```py
r = early_records[0]
r['t1'] = time.time()  # now
r['t2'] = r['t1'] + 1440  # keep duration
update_record(r)
```

**Comment by InteractionEngineer** [comment]
It work's again! Thank you so much! 🎉

**Comment by almarklein** [comment]
Thanks for your patience to work this out together!

I'm glad we were able to figure it out. I already made a few changes to prevent this from happening to other users. Will make a release shortly.

I'll also add some "diagnostic" commands to the CLI tool, based on the code samples we developed here.

**Comment by almarklein** [comment]
#22
