### ISSUE TITLE
Better support for resuming records

### ISSUE THREAD

**Issue by Saatvik-Lochan** [almarklein/timetagger#508]
I take short and frequent breaks. Currently I have to click on the record and click 'Resume' - it would be nice if I could just press `c` for 'continue'. 

Additionally this means I end up with many small records with the same name and the UI becomes a bit cluttered. An idea might be to only have the name of the first record appear if there are many adjacent records in the same view with the exact same name.

**Comment by dsseng** [comment]
Actually pressing Shift+S allows you to resume the most recent record. But yes, it'd be nice to only have one label per many adjacent records

**Comment by almarklein** [comment]
Thanks for this issue!

The `ctrl+S` should solve the first problem you mention. The second problem is also listed in  #513, let's track it there (the gif is helpful to see the problem).
