### ISSUE TITLE
add additional text box for detailed notes

### ISSUE THREAD

**Issue by mrkrnz** [almarklein/timetagger#512]
It would be good to have an additional text box to add notes for the record most logically when stopping the record so that it will be keeping detailed information about the record, the point you stopped the record, some ideas, or a summary of work you did.

**Comment by Tagirijus** [comment]
You do not have to use only tags. You can also just write text in the same field as the texts. You could use this for that purpose you mentioned, I guess.

**Comment by mrkrnz** [comment]
It is not about mentioning the purpose. For instance, I am working on a Jira ticket, and creating the record as '#jira working on this',    but when I stop it, I want to be able to summarize what I did and where I left over. Knowing where I left over would be also good, as it can give an hint when I want to resume the record next time.
