### ISSUE TITLE
[500] Error returning access token for localhost

### ISSUE THREAD

**Issue by edgardleal** [almarklein/timetagger#85]
I received the following error when trying to get an access token for localhost.

![image](https://user-images.githubusercontent.com/1612250/119739979-776e0d80-be59-11eb-856d-892c5f7d8902.png)

**Comment by almarklein** [comment]
Thanks for the report!

Is this when you're on the account page? Could you show the part of the traceback above this, which show the frames in timetagger where the error originates?

**Comment by edgardleal** [comment]
Here is the screen where I received the error.

![image](https://user-images.githubusercontent.com/1612250/119816740-707be500-bec3-11eb-9a65-dd089406324b.png)


I think that the `jwt.encode` method is returning `bytes` instead `string` as reported in this issue https://github.com/jpadilla/pyjwt/issues/391

Now, I am running the project with the following modification:

![image](https://user-images.githubusercontent.com/1612250/119817287-2d6e4180-bec4-11eb-9335-e573b00109c8.png)

I know that it was fixed in version [2.1.0](https://github.com/jpadilla/pyjwt/commit/e3a1ba52b5926bd419a5bab73c64d7bce1089958), but I don't know why, `pip install --upgrade pyjwt` away keep the version `1.7.0`

Should I create a PR with this modification?

**Comment by almarklein** [comment]
Ah, great to see you've already found the cause ... and a solution. A PR would be great!

**Comment by almarklein** [comment]
BTW, utf-8 is the default, so you can just do `result.decode()`
