### ISSUE TITLE
setup expected work time per week and get status

### ISSUE THREAD

**Issue by Floehe** [almarklein/timetagger#92]
Hi,

It would be great if one could setup your personal expected work time per week (like 40 hours). and get an overview how much of this time has already passed in the running week, respectively how much will be left to work.

All the best,
Florian

**Comment by almarklein** [comment]
Thanks for the interesting suggestion!

I bet you already know this, but for the record, you get a week overview if you select "this week" in the time range drop-down (see image).
![image](https://user-images.githubusercontent.com/3015475/127343939-6f2b0ea5-4aa6-4de7-b071-495b8c3bf42d.png)

The proposal, as I understand it, is to show a number, or perhaps a percentage that shows hours logged vs a certain target. I can see that being useful, but there are also many questions to explore - let's discuss :)

Some questions I have now:

* For a feature like this, I expect some people want to set a target for a specific tag.
* Should we support multiple targets?
* How/where/when should we display these targets?
  * Always visible - hard to do if we want to support multiple targets.
  * Show targets separately in the overview area when the week view is selected.
  * Show target for a tag when that tag is selected.
  * ...

**Comment by Floehe** [comment]
Yes I already found that total number in the week overview. And that would be exactly the place where I imagined to get a quick look at how much time I have invested this week already and how much is left until the hours of the week are completed.

Personally I wouldn't need this for different tags, but maybe could be useful for others, who have a fixed pool of hours, that can go into one specific tag.

My situation: I have a fix employment contract, where I have to do exactly 38,5 hours a week. When I work 8 hours on Monday and 9 on Tuesday, I would like to know, how many hours are left for this week and when I can finish early on Friday :)

**Comment by almarklein** [comment]
So if I understand correctly, if the week view would show `target_hours - spent_hours` for your set target, in addition to the spent hours shown now, you'd be happy, right? I think something in this direction is viable.

**Comment by Floehe** [comment]
that would make me very happy! :)

**Comment by HexaCubist** [comment]
Chiming in that this would be cool to see! Expanding a little, I was just about to write my own script to check how I'm tracking in surplus/deficit of expected hours over the previous X period of time. This looks like a request for what I was about to make!

For me, it would be useful to separate this by tag as that's how I track different timecodes and contracts, and it would be good if I could say "X hours per week" and then zoom out to arbitrary dates (eg a month/year) to see how many hours ahead/behind I am for that time period.

Right now, it's hard to get a grip on these numbers if it says I did X hours between two dates (that might not neatly break down into a whole number of weeks, and may be over several months), and I am having to manually do the math to calculate expected hours for the same time period.

**Comment by almarklein** [comment]
@HexaCubist thanks for your comment! This helps me make it more clear how this should be implemented.

**Comment by almarklein** [comment]
Today I finished the work that I started earlier for this feature. It's released and deployed.

You can now set targets for tags (and combinations of tags) by clicking on the target icon when you have the tag selected in the analytics panel. Have a go, and let me know whether this covers your needs, and/or you think that it may be improved!
